<?php
/**
 * @file
 * Holds install and update hooks for our language switcher implementation.
 */

/**
 * Implements hook_install().
 *
 * This install hook makes sure that the weight of this module is higher tran
 * the base module.
 */
function dt_language_selector_site_popup_install() {
  db_update('system')
    ->fields(array('weight' => 999))
    ->condition('name', 'dt_language_selector_site_popup', '=')
    ->execute();
}
