<?php
/**
 * @file
 * This file contains the shared functions between dt_core and cwt_core.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Alters the exposed form to include some additional logic.
 */
function dt_shared_functions_form_views_exposed_form_alter(&$form, &$form_state) {
  if (!$form_state['submitted']) {
    // Hide the button, but only when js is available.
    if (isset($form['reset']) && !empty($form['reset'])) {
      $form['reset']['#attributes']['class'][] = 'js-hide';
      $form['reset']['#attributes']['class'][] = 'js-showonsubmit';
    }
  }
}

/**
 * Implements hook_ajax_render_alter().
 *
 * Hide the showonsubmit button after the ajax request.
 */
function dt_shared_functions_ajax_render_alter(&$commands) {
  $commands[] = ajax_command_invoke('.js-showonsubmit', 'show');
}
