<?php
/**
 * @file
 * nexteuropa_formatters.module
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function nexteuropa_formatters_ctools_plugin_api($module, $api) {
  if ($module == 'field_group' && $api == 'field_group') {
    return array('version' => 1);
  }
}

/**
 * Implements hook_field_group_formatter_info().
 */
function nexteuropa_formatters_field_group_formatter_info() {
  $formatters = array();

  $formatters['meta_wrapper'] = array(
    'label' => t('Meta Wrapper'),
    'description' => t('This fieldgroup renders meta component wrapper'),
    'instance_settings' => array('classes' => ''),
  );

  foreach (array_keys($formatters) as $key) {
    $formatter = &$formatters[$key];
    $formatter['instance_settings']['required_fields'] = 1;
  }

  return array(
    'form' => $formatters,
    'display' => $formatters,
  );
}

/**
 * Implements hook_field_group_pre_render().
 */
function nexteuropa_formatters_field_group_pre_render(&$element, $group, &$form) {
  // You can prepare some variables to use in the logic.
  $view_mode = isset($form['#view_mode']) ? $form['#view_mode'] : 'form';
  $id = $form['#entity_type'] . '_' . $form['#bundle'] . '_' . $view_mode . '_' . $group->group_name;

  // Each formatter type can have whole different set of element properties.
  switch ($group->format_type) {
    // Normal or collapsible div.
    case 'meta_wrapper':
      $add = array(
        '#type' => 'markup',
        '#weight' => $group->weight,
        '#id' => $id,
      );

      $classes = ' ' . $group->format_settings['instance_settings']['classes'];
      $add['#prefix'] = '<div class="meta' . $classes . '">';
      $add['#suffix'] = '</div>';

      $element += $add;
      break;
  }
}
