<?php
/**
 * @file
 * nexteuropa_formatters.module
 */

require_once 'nexteuropa_formatters.field.inc';
require_once 'nexteuropa_formatters.field_group.inc';

/**
 * Implements hook_theme().
 */
function nexteuropa_formatters_theme($existing, $type, $theme, $path) {
  return array(
    'nexteuropa_bem_item_list' => array(
      'file' => 'nexteuropa_formatters.theme.inc',
      'variables' => array(
        'items' => array(),
        'modifiers' => array(),
        'type' => 'div',
        'attributes' => array(),
      ),
    ),
  );
}

/**
 * Helper function to return the context nav prefix.
 *
 * @param string $label
 *   The label to be used in the prefix.
 *
 * @return array
 *   #prefix and #suffix element for the render object.
 */
function _nexteuropa_formatters_get_context_nav_wrapper($label) {
  return array(
    '#prefix' => '<span class="context-nav__label">' . $label . '</span><div class="context-nav__items">',
    '#suffix' => '</div>',
  );
}
