<?php

/**
 * @file
 * Code for the DT NAL resource types feature.
 */

include_once 'dt_nal_resource_types.features.inc';
include_once 'dt_nal_resource_types.helpers.inc';

/**
 * Implements hook_feeds_presave().
 */
function dt_nal_resource_types_feeds_presave(FeedsSource $source, $entity, $item) {
  if ($source->importer->id == 'nal_resource_types') {
    $resource_types = _dt_nal_resource_types_list();
    $authority_code = $entity->field_authority_code[LANGUAGE_NONE][0]['value'];
    if (!in_array($authority_code, $resource_types)) {
      $entity->feeds_item->skip = TRUE;
    }
  }
}
