<?php
/**
 * @file
 * Code for the DT Priority input feature.
 */

include_once 'dt_priority.features.inc';

/**
 * Implements hook_menu().
 */
function dt_priority_menu() {
  $items = array();

  $items['admin/config/system/dt-priority-settings'] = array(
    'access arguments' => array('administer site configuration'),
    'description' => t('Setting the ID of the node to display the priority listing on.'),
    'file' => 'dt_priority.admin.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dt_priority_settings'),
    'title' => t('Priority page settings'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * We alter the weight options to only allow 0-10.
 */
function dt_priority_form_priority_node_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form['weight'])) {
    foreach ($form['weight']['weight_weight']["#options"] as $key => $value) {
      if (substr($key, 0, 1) == '-') {
        unset($form['weight']['weight_weight']["#options"][$key]);
      }
    }
  }
}
