<?php
/**
 * @file
 * Code for the Featured item feature.
 */

include_once 'dt_featured_item.features.inc';

/**
 * Implements hook_node_view().
 *
 * Remove the title from our display.
 */
function dt_featured_item_node_view($node, $view_mode, $langcode) {
  // We should only alter the featured item teaser..
  if ($node->type == 'featured_item') {

    // Get our node as metadata wrapper, so we dont have to check for languages.
    $node_wrapper = entity_metadata_wrapper('node', $node);

    // If both of the fields are present with data.
    if ($node_wrapper->field_feat_item_ref_or_url->value() && $button_label = $node_wrapper->field_feat_item_button_label->value()) {

      // Get our values.
      $button_link = $node_wrapper->field_feat_item_ref_or_url->value();

      // Build our link.
      $link = l(
        $button_label,
        $button_link['url'],
        array(
          'attributes' => array(
            'class' => array(
              'btn',
              'btn-ctn',
            ),
          ),
        )
      );

      // Populate the content.
      $node->content['field_feat_item_button_label'][0]['#markup'] = $link;
    }
  }
}
