<?php
/**
 * @file
 * Dt_featured_item install file.
 */

/**
 * Implements hook_install().
 */
function dt_featured_item_install() {
  // Apply default dt configuration to "Featured item" content type.
  multisite_config_service('nexteuropa_core')->applyDefaultConfigurationToContentType('featured_item');
}

/**
 * Revert feature to make changes take effect.
 */
function dt_featured_item_update_7101() {
  features_revert_module('Dt_featured_item');
}
