<?php
/**
 * @file
 * dt_featured_item.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function dt_featured_item_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "ds" && $api == "ds") {
    return array("version" => "1");
  }
  if ($module == "field_group" && $api == "field_group") {
    return array("version" => "1");
  }
  if ($module == "picture" && $api == "default_picture_mapping") {
    return array("version" => "2");
  }
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_image_default_styles().
 */
function dt_featured_item_image_default_styles() {
  $styles = array();

  // Exported image style: featured_item.
  $styles['featured_item'] = array(
    'name' => 'featured_item',
    'label' => 'Featured Item',
    'effects' => array(
      1 => array(
        'label' => 'Scale',
        'help' => 'Scaling will maintain the aspect-ratio of the original image. If only a single dimension is specified, the other dimension will be calculated.',
        'effect callback' => 'retina_images_image_scale_effect',
        'dimensions callback' => 'image_scale_dimensions',
        'form callback' => 'retina_images_image_scale_form',
        'summary theme' => 'retina_images_image_scale_summary',
        'module' => 'image',
        'name' => 'image_scale',
        'data' => array(
          'width' => 300,
          'height' => '',
          'upscale' => 0,
          'retinafy' => 0,
        ),
        'weight' => 1,
      ),
    ),
  );

  // Exported image style: featured_item_responsivebreakpoints_theme_europa_medium_1x.
  $styles['featured_item_responsivebreakpoints_theme_europa_medium_1x'] = array(
    'name' => 'featured_item_responsivebreakpoints_theme_europa_medium_1x',
    'label' => 'featured_item_responsivebreakpoints_theme_europa_medium_1x',
    'effects' => array(
      8 => array(
        'label' => 'Scale',
        'help' => 'Scaling will maintain the aspect-ratio of the original image. If only a single dimension is specified, the other dimension will be calculated.',
        'effect callback' => 'retina_images_image_scale_effect',
        'dimensions callback' => 'image_scale_dimensions',
        'form callback' => 'retina_images_image_scale_form',
        'summary theme' => 'retina_images_image_scale_summary',
        'module' => 'image',
        'name' => 'image_scale',
        'data' => array(
          'width' => 300,
          'height' => '',
          'upscale' => 0,
          'retinafy' => 0,
        ),
        'weight' => 1,
      ),
    ),
  );

  // Exported image style: featured_item_responsivebreakpoints_theme_europa_medium_2x.
  $styles['featured_item_responsivebreakpoints_theme_europa_medium_2x'] = array(
    'name' => 'featured_item_responsivebreakpoints_theme_europa_medium_2x',
    'label' => 'featured_item_responsivebreakpoints_theme_europa_medium_2x',
    'effects' => array(
      7 => array(
        'label' => 'Scale',
        'help' => 'Scaling will maintain the aspect-ratio of the original image. If only a single dimension is specified, the other dimension will be calculated.',
        'effect callback' => 'retina_images_image_scale_effect',
        'dimensions callback' => 'image_scale_dimensions',
        'form callback' => 'retina_images_image_scale_form',
        'summary theme' => 'retina_images_image_scale_summary',
        'module' => 'image',
        'name' => 'image_scale',
        'data' => array(
          'width' => 300,
          'height' => '',
          'upscale' => 0,
          'retinafy' => 0,
        ),
        'weight' => 1,
      ),
    ),
  );

  // Exported image style: featured_item_responsivebreakpoints_theme_europa_mobile_1x.
  $styles['featured_item_responsivebreakpoints_theme_europa_mobile_1x'] = array(
    'name' => 'featured_item_responsivebreakpoints_theme_europa_mobile_1x',
    'label' => 'featured_item_responsivebreakpoints_theme_europa_mobile_1x',
    'effects' => array(
      12 => array(
        'label' => 'Scale',
        'help' => 'Scaling will maintain the aspect-ratio of the original image. If only a single dimension is specified, the other dimension will be calculated.',
        'effect callback' => 'retina_images_image_scale_effect',
        'dimensions callback' => 'image_scale_dimensions',
        'form callback' => 'retina_images_image_scale_form',
        'summary theme' => 'retina_images_image_scale_summary',
        'module' => 'image',
        'name' => 'image_scale',
        'data' => array(
          'width' => 300,
          'height' => '',
          'upscale' => 0,
          'retinafy' => 0,
        ),
        'weight' => 1,
      ),
    ),
  );

  // Exported image style: featured_item_responsivebreakpoints_theme_europa_mobile_2x.
  $styles['featured_item_responsivebreakpoints_theme_europa_mobile_2x'] = array(
    'name' => 'featured_item_responsivebreakpoints_theme_europa_mobile_2x',
    'label' => 'featured_item_responsivebreakpoints_theme_europa_mobile_2x',
    'effects' => array(
      11 => array(
        'label' => 'Scale',
        'help' => 'Scaling will maintain the aspect-ratio of the original image. If only a single dimension is specified, the other dimension will be calculated.',
        'effect callback' => 'retina_images_image_scale_effect',
        'dimensions callback' => 'image_scale_dimensions',
        'form callback' => 'retina_images_image_scale_form',
        'summary theme' => 'retina_images_image_scale_summary',
        'module' => 'image',
        'name' => 'image_scale',
        'data' => array(
          'width' => 300,
          'height' => '',
          'upscale' => 0,
          'retinafy' => 0,
        ),
        'weight' => 1,
      ),
    ),
  );

  // Exported image style: featured_item_responsivebreakpoints_theme_europa_narrow_1x.
  $styles['featured_item_responsivebreakpoints_theme_europa_narrow_1x'] = array(
    'name' => 'featured_item_responsivebreakpoints_theme_europa_narrow_1x',
    'label' => 'featured_item_responsivebreakpoints_theme_europa_narrow_1x',
    'effects' => array(
      10 => array(
        'label' => 'Scale',
        'help' => 'Scaling will maintain the aspect-ratio of the original image. If only a single dimension is specified, the other dimension will be calculated.',
        'effect callback' => 'retina_images_image_scale_effect',
        'dimensions callback' => 'image_scale_dimensions',
        'form callback' => 'retina_images_image_scale_form',
        'summary theme' => 'retina_images_image_scale_summary',
        'module' => 'image',
        'name' => 'image_scale',
        'data' => array(
          'width' => 300,
          'height' => '',
          'upscale' => 0,
          'retinafy' => 0,
        ),
        'weight' => 1,
      ),
    ),
  );

  // Exported image style: featured_item_responsivebreakpoints_theme_europa_narrow_2x.
  $styles['featured_item_responsivebreakpoints_theme_europa_narrow_2x'] = array(
    'name' => 'featured_item_responsivebreakpoints_theme_europa_narrow_2x',
    'label' => 'featured_item_responsivebreakpoints_theme_europa_narrow_2x',
    'effects' => array(
      9 => array(
        'label' => 'Scale',
        'help' => 'Scaling will maintain the aspect-ratio of the original image. If only a single dimension is specified, the other dimension will be calculated.',
        'effect callback' => 'retina_images_image_scale_effect',
        'dimensions callback' => 'image_scale_dimensions',
        'form callback' => 'retina_images_image_scale_form',
        'summary theme' => 'retina_images_image_scale_summary',
        'module' => 'image',
        'name' => 'image_scale',
        'data' => array(
          'width' => 300,
          'height' => '',
          'upscale' => 0,
          'retinafy' => 0,
        ),
        'weight' => 1,
      ),
    ),
  );

  // Exported image style: featured_item_responsivebreakpoints_theme_europa_normal_1x.
  $styles['featured_item_responsivebreakpoints_theme_europa_normal_1x'] = array(
    'name' => 'featured_item_responsivebreakpoints_theme_europa_normal_1x',
    'label' => 'featured_item_responsivebreakpoints_theme_europa_normal_1x',
    'effects' => array(
      6 => array(
        'label' => 'Scale',
        'help' => 'Scaling will maintain the aspect-ratio of the original image. If only a single dimension is specified, the other dimension will be calculated.',
        'effect callback' => 'retina_images_image_scale_effect',
        'dimensions callback' => 'image_scale_dimensions',
        'form callback' => 'retina_images_image_scale_form',
        'summary theme' => 'retina_images_image_scale_summary',
        'module' => 'image',
        'name' => 'image_scale',
        'data' => array(
          'width' => 300,
          'height' => '',
          'upscale' => 0,
          'retinafy' => 0,
        ),
        'weight' => 1,
      ),
    ),
  );

  // Exported image style: featured_item_responsivebreakpoints_theme_europa_normal_2x.
  $styles['featured_item_responsivebreakpoints_theme_europa_normal_2x'] = array(
    'name' => 'featured_item_responsivebreakpoints_theme_europa_normal_2x',
    'label' => 'featured_item_responsivebreakpoints_theme_europa_normal_2x',
    'effects' => array(
      5 => array(
        'label' => 'Scale',
        'help' => 'Scaling will maintain the aspect-ratio of the original image. If only a single dimension is specified, the other dimension will be calculated.',
        'effect callback' => 'retina_images_image_scale_effect',
        'dimensions callback' => 'image_scale_dimensions',
        'form callback' => 'retina_images_image_scale_form',
        'summary theme' => 'retina_images_image_scale_summary',
        'module' => 'image',
        'name' => 'image_scale',
        'data' => array(
          'width' => 300,
          'height' => '',
          'upscale' => 0,
          'retinafy' => 0,
        ),
        'weight' => 1,
      ),
    ),
  );

  // Exported image style: featured_item_responsivebreakpoints_theme_europa_wide_1x.
  $styles['featured_item_responsivebreakpoints_theme_europa_wide_1x'] = array(
    'name' => 'featured_item_responsivebreakpoints_theme_europa_wide_1x',
    'label' => 'featured_item_responsivebreakpoints_theme_europa_wide_1x',
    'effects' => array(
      3 => array(
        'label' => 'Scale',
        'help' => 'Scaling will maintain the aspect-ratio of the original image. If only a single dimension is specified, the other dimension will be calculated.',
        'effect callback' => 'retina_images_image_scale_effect',
        'dimensions callback' => 'image_scale_dimensions',
        'form callback' => 'retina_images_image_scale_form',
        'summary theme' => 'retina_images_image_scale_summary',
        'module' => 'image',
        'name' => 'image_scale',
        'data' => array(
          'width' => 300,
          'height' => '',
          'upscale' => 0,
          'retinafy' => 0,
        ),
        'weight' => 1,
      ),
    ),
  );

  // Exported image style: featured_item_responsivebreakpoints_theme_europa_wide_2x.
  $styles['featured_item_responsivebreakpoints_theme_europa_wide_2x'] = array(
    'name' => 'featured_item_responsivebreakpoints_theme_europa_wide_2x',
    'label' => 'featured_item_responsivebreakpoints_theme_europa_wide_2x',
    'effects' => array(
      2 => array(
        'label' => 'Scale',
        'help' => 'Scaling will maintain the aspect-ratio of the original image. If only a single dimension is specified, the other dimension will be calculated.',
        'effect callback' => 'retina_images_image_scale_effect',
        'dimensions callback' => 'image_scale_dimensions',
        'form callback' => 'retina_images_image_scale_form',
        'summary theme' => 'retina_images_image_scale_summary',
        'module' => 'image',
        'name' => 'image_scale',
        'data' => array(
          'width' => 300,
          'height' => '',
          'upscale' => 0,
          'retinafy' => 0,
        ),
        'weight' => 1,
      ),
    ),
  );

  // Exported image style: featured_item_responsivemodule_picture_empty_srcset_1x.
  $styles['featured_item_responsivemodule_picture_empty_srcset_1x'] = array(
    'name' => 'featured_item_responsivemodule_picture_empty_srcset_1x',
    'label' => 'featured_item_responsivemodule_picture_empty_srcset_1x',
    'effects' => array(
      4 => array(
        'label' => 'Scale',
        'help' => 'Scaling will maintain the aspect-ratio of the original image. If only a single dimension is specified, the other dimension will be calculated.',
        'effect callback' => 'retina_images_image_scale_effect',
        'dimensions callback' => 'image_scale_dimensions',
        'form callback' => 'retina_images_image_scale_form',
        'summary theme' => 'retina_images_image_scale_summary',
        'module' => 'image',
        'name' => 'image_scale',
        'data' => array(
          'width' => 300,
          'height' => '',
          'upscale' => 0,
          'retinafy' => 0,
        ),
        'weight' => 1,
      ),
    ),
  );

  return $styles;
}

/**
 * Implements hook_node_info().
 */
function dt_featured_item_node_info() {
  $items = array(
    'featured_item' => array(
      'name' => t('Featured item'),
      'base' => 'node_content',
      'description' => t('Featured item content type.'),
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
  );
  drupal_alter('node_info', $items);
  return $items;
}
