<?php
/**
 * @file
 * Code for the Featured item feature.
 */

include_once 'dt_featured_item.features.inc';

/**
 * Implements hook_node_view().
 */
function dt_featured_item_entity_load($entities, $type) {
  _dt_featured_item_load_entities($entities, $type);
}

/**
 * Implements hook_entitycache_ENTITY_TYPE_load().
 */
function dt_featured_item_entitycache_node_load($entities) {
  _dt_featured_item_load_entities($entities, 'node');
}

/**
 * Alter legacy link on entity load.
 */
function _dt_featured_item_load_entities($entities, $type) {
  if ($type == 'node') {
    foreach ($entities as $entity) {
      // If the featured item has an entity reference set, override the
      // legacy link value with a link to the target.
      if ($entity->type == 'featured_item' && isset($entity->field_feat_item_reference[LANGUAGE_NONE][0]['target_id'])) {
        $entity->legacy = url('node/' . $entity->field_feat_item_reference[LANGUAGE_NONE][0]['target_id']);
      }
    }
  }
}
