<?php
/**
 * @file
 * Code for the Featured item feature.
 */

include_once 'dt_featured_item.features.inc';

/**
 * Implements hook_node_view().
 */
function dt_featured_item_entity_load($entities, $type) {
  if ($type == 'node') {
    foreach ($entities as &$node) {
      if ($node->type == 'featured_item' && isset($node->field_feat_item_reference[LANGUAGE_NONE][0]['target_id'])) {
        $node->legacy = 'node/' . $node->field_feat_item_reference[LANGUAGE_NONE][0]['target_id'];
      }
    }
  }
}
