<?php

/**
 * @file
 * Install file.
 */

/**
 * Implements hook_install().
 */
function dt_pri_policy_area_install() {
  // Apply info dt configuration to "Policy input" content type.
  multisite_config_service('nexteuropa_core')->applyDefaultConfigurationToContentType('priority_policy_area');
}

/**
 * Implements hook_uninstall().
 */
function dt_pri_policy_area_uninstall() {
  drupal_set_message(t('NextEuropa priority_policy_area feature is uninstalled on your site.'));
}
