<?php
/**
 * @file
 * Code for the Core feature.
 */

include_once 'dt_core.features.inc';

/**
 * No source field Exception.
 */
class DTCoreSourceFieldError extends Exception {}

/**
 * No destionation field Exception.
 */
class DTCoreDestinationFieldError extends Exception {}

/**
 * Fields are of same tye Exception.
 */
class DTCoreFieldTypeAreNotSame extends Exception {}

/**
 * Circular reference Exception.
 */
class DTCoreParentCircular extends Exception {}

/**
 * Implements hook_field_widget_form_alter().
 */
function dt_core_field_widget_form_alter(&$element, &$form_state, $context) {
  if ($context['field']['type'] == 'entityreference') {
    if ($context['field']['settings']['target_type'] == 'node' && !empty($context['field']['settings']['handler_settings']['target_bundles'])) {
      $types = $context['field']['settings']['handler_settings']['target_bundles'];
      $types_count = count($types);
      $links = '';
      $i = 0;
      $separator = ',';
      foreach ($types as $machine_name) {
        $type = node_type_get_type($machine_name);
        $current_separator = $types_count > 1 && $i == $types_count - 2 ? ' ' . t('or') : $separator;
        $links .= l($type->name, 'node/add/' . str_replace('_', '-', $machine_name), array('attributes' => array('target' => '_blank'))) . $current_separator . ' ';
        $i++;
      }
      $links = rtrim($links, $separator . ' ');
      $description = '<p>' . t('In case the content you try to refer to does not exist yet you can create it by going to !links.', array('!links' => $links)) . '</p>';
      if (isset($element['target_id'])) {
        $element['target_id']['#description'] = $description . $element['target_id']['#description'];
      }
      else {
        $element['#description'] = $description . $element['#description'];
      }
    }
  }
}

/**
 * Implements hook_block_info().
 */
function dt_core_block_info() {
  $blocks['dt_block_copyright'] = array(
    'info' => t('Copyright paragraph'),
  );

  $blocks['dt_header_site_tab_switcher'] = array(
    'info' => t('Header site tab switcher'),
  );

  $blocks['dt_footer_site_tab_switcher'] = array(
    'info' => t('Footer site tab switcher'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function dt_core_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'dt_block_copyright':
    case 'dt_header_site_tab_switcher':
    case 'dt_footer_site_tab_switcher':
      $block['content'] = dt_core_get_blocks_content($delta);
      break;
  }
  return $block;
}

/**
 * A module-defined block content function.
 */
function dt_core_get_blocks_content($delta) {
  $result = array();
  switch ($delta) {
    case 'dt_block_copyright':
      $result = array(
        '#markup' => "<div class='footer__disclaimer'><span>" . t('© European Commission 2015') . "</span></div>",
      );
      break;

    case 'dt_header_site_tab_switcher':
      $result = array(
        '#markup' => theme('site_switcher_tabs', array('modifier' => 'site-switcher--header')),
      );
      break;

    case 'dt_footer_site_tab_switcher':
      $result = array(
        '#markup' => theme('site_switcher_tabs', array('modifier' => 'site-switcher--footer')),
      );
      break;
  }
  return $result;
}

/**
 * Implements hook_theme().
 */
function dt_core_theme($existing, $type, $theme, $path) {
  return array(
    'site_switcher_tabs' => array(
      'file' => 'dt_core.theme.inc',
      'variables' => array(
        'modifier' => NULL,
      ),
    ),
  );
}

/**
 * Helper to add initial set of buttons on the default profile of the Full HTML.
 */
function dt_apply_wysiwyg_buttons() {
  // Enable a set of CKEditor buttons for DT project on the "Full HTML" profile.
  $default = array(
    'Anchor',
    'Bold',
    'Italic',
    'Underline',
    'Format',
    'JustifyBlock',
    'JustifyCenter',
    'JustifyLeft',
    'JustifyRight',
    'Indent',
    'Outdent',
    'Blockquote',
    'Font',
    'Table',
    'BulletedList',
    'NumberedList',
    'Link',
    'Unlink',
    'Source',
    'PasteFromWord',
    'Undo',
    'ShowBlocks',
  );
  multisite_config_service('wysiwyg')->addButtonsToProfile('full_html', 'default', $default);

  $lite = array(
    'lite_AcceptAll',
    'lite_RejectOne',
    'lite_RejectAll',
    'lite_ToggleShow',
    'lite_AcceptOne',
    'lite_ToggleTracking',
  );
  multisite_config_service('wysiwyg')->addButtonsToProfile('full_html', 'lite', $lite);
}

/**
 * Copy values from source to destination filed.
 *
 * @param string $entity_type
 *   The type of entity, like: node.
 * @param string $bundle
 *   Entity bundle, like: page.
 * @param string $source_field_name
 *   Source field name, like: field_core_link.
 * @param string $destination_field_name
 *   Destination field, like: field_core_links.
 *
 * @throws \DTCoreSourceFieldError
 *   Exception when no source field with the given name.
 * @throws \DTCoreDestinationFieldError
 *   Exception when no destination field with the given name.
 * @throws \DTCoreFieldTypeAreNotSame
 *   Exception when source and destination are not the same field type.
 */
function _dt_core_field_value_copy($entity_type, $bundle, $source_field_name, $destination_field_name) {
  // Source and destination field info.
  $source_field_info = field_info_field($source_field_name);
  $destination_field_info = field_info_field($destination_field_name);

  // Error handling.
  if (!$source_field_info) {
    throw new DTCoreSourceFieldError(
      t('There is not any %source (source field) with this name.', array(
        '%source' => $source_field_name,
      ))
    );
  }
  if (!$destination_field_info) {
    throw new DTCoreDestinationFieldError(
      t('There is not any %source (source field) with this name.', array(
        '%source' => $destination_field_name,
      ))
    );
  }
  if ($source_field_info['type'] != $destination_field_info['type']) {
    throw new DTCoreFieldTypeAreNotSame(
      t('%source (source) and %destination (destination) are not the same field type.', array(
        '%source' => $source_field_name,
        '%destination' => $destination_field_name,
      ))
    );
  }
  // Source field  is a multiple one.
  $source_field_is_multiple = ($source_field_info['cardinality'] != 1) ? TRUE : FALSE;
  // Destination field is a multiple one.
  $destination_field_is_multiple = ($destination_field_info['cardinality'] != 1) ? TRUE : FALSE;

  // Query the entities.
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', $entity_type)
    ->entityCondition('bundle', $bundle);
  $result = $query->execute();

  // Use the result if any.
  if (isset($result[$entity_type])) {
    // Get the entity ids from result.
    $ids = array_keys($result[$entity_type]);
    // Load entities using ids.
    $entities = entity_load($entity_type, $ids, array(), TRUE);
    foreach ($entities as $entity) {
      $entity_wrapper = entity_metadata_wrapper($entity_type, $entity);

      // Check the source field for value.
      if (
        isset($entity_wrapper->$source_field_name)
        && $entity_wrapper->$source_field_name->value()
        && $entity_wrapper->$destination_field_name->value() == NULL
      ) {
        // Same cardinality.
        if ($source_field_is_multiple == $destination_field_is_multiple) {
          $entity_wrapper->$destination_field_name = $entity_wrapper->$source_field_name->value();
        }
        // Source is multiple field, but destination not,
        // than take the first element.
        elseif ($source_field_is_multiple && !$destination_field_is_multiple) {
          $entity_wrapper->$destination_field_name = reset($entity_wrapper->$source_field_name->value());
        }
        // Source is single element field, but destination not,
        // than use an array wrapper.
        else {
          // Take the first item of array.
          $entity_wrapper->$destination_field_name = array($entity_wrapper->$source_field_name->value());
        }
        $entity_wrapper->save();
      }
    }
  }
}

/**
 * Nodes that will have their alias re-generated on hook_exit().
 */
$GLOBALS['dt_core_nodes_to_update_alias'] = array();

/**
 * Fields that can be used in URL patterns to define hierarchy.
 */
$GLOBALS['dt_core_parent_fields'] = array(
  'field_core_parent',
  'field_core_policy_area',
);

/**
 * Implements function hook_path_insert().
 */
function dt_core_path_insert($path) {
  _dt_core_path_update_relatives($path);
}

/**
 * Implements function hook_path_update().
 */
function dt_core_path_update($path) {
  _dt_core_path_update_relatives($path);
}

/**
 * Updates aliases of parent | child nodes.
 */
function _dt_core_path_update_relatives($path) {
  $source = explode('/', $path['source']);
  if ($source[0] == 'node') {
    $nid = $source[1];

    foreach ($GLOBALS['dt_core_parent_fields'] as $field_name) {
      // Find children based on field.
      $children = _dt_core_node_get_relatives($nid, $field_name);
      // Add current as first to force re-generate as first.
      if (!empty($parents)) {
        array_unshift($children, $nid);
      }

      // Find parents based on field.
      $parents = _dt_core_node_get_relatives($nid, $field_name, 'parents', TRUE);
      // Add current as last to force re-generate as last.
      if (!empty($parents)) {
        $parents[] = $nid;
      }

      $relatives = array_merge($parents, $children);
      if (!empty($relatives)) {
        $GLOBALS['dt_core_nodes_to_update_alias'][$nid] = $relatives;
      }
    }
  }
}

/**
 * Finds child|parent nodes based on entity reference.
 *
 * Only a few entity reference fields can be used to define parent relationship.
 * These fields are stored in the $GLOBALS['dt_core_parent_fields'].
 *
 * @param int $nid
 *   Node id.
 * @param string $field_name
 *   Field name that is used for hierarchy.
 * @param string $direction
 *   Children or parents.
 * @param bool $no_alias_only
 *   Exclude nodes that already have an alias.
 * @param int $original_nid
 *   Node id of the starting item.
 *
 * @return array
 *   Node ids of children|parents
 *
 * @see $GLOBALS['dt_core_parent_fields']
 */
function _dt_core_node_get_relatives($nid, $field_name, $direction = 'children', $no_alias_only = FALSE, $original_nid = NULL) {
  if (!isset($field_name)) {
    return array();
  }
  $original_nid = !$original_nid ? $nid : $original_nid;
  $affected_nodes = array();

  if ($direction == 'parents') {
    $result = db_select('field_data_' . $field_name, 'p')
      ->fields('p', array($field_name . '_target_id'))
      ->condition('entity_id', $nid, '=')
      ->execute()
      ->fetchAssoc();

    $nids = $result ? array_values($result) : FALSE;
    // Check if parent has already an alias.
    if ($nids) {
      if ($no_alias_only && drupal_get_path_alias('node/' . $nids[0]) != ('node/' . $nids[0])) {
        return array();
      }

      // Item is among its own parents.
      if (in_array($original_nid, $nids)) {
        throw new DTCoreParentCircular(
          t('Node !nid is among its own parents', array(
            '!nid' => $original_nid,
          ))
        );
      }
    }
  }
  // Children need to be updated always.
  else {
    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'node')
      ->fieldCondition($field_name, 'target_id', $nid, '=');

    $result = $query->execute();
    $nids = isset($result['node']) ? array_keys($result['node']) : FALSE;
  }

  if ($nids) {
    foreach ($nids as $ref_nid) {
      if (isset($result['node'][$ref_nid])) {
        // URL pattern for node type.
        $pattern = pathauto_pattern_load_by_entity('node', $result['node'][$ref_nid]->type);
        // If current child URL is not using the field in alias pattern, skip.
        if (!_dt_core_parent_field_in_pattern($field_name, $pattern)) {
          continue;
        }
      }

      // Find relatives.
      $referenced = _dt_core_node_get_relatives($ref_nid, $field_name, $direction, $no_alias_only, $original_nid);
      // Add the to the list in the appropriate order based on direction.
      if ($direction == 'parents') {
        $affected_nodes = array_merge($affected_nodes, $referenced);
        $affected_nodes[] = $ref_nid;
      }
      else {
        $affected_nodes[] = $ref_nid;
        $affected_nodes = array_merge($affected_nodes, $referenced);
      }
    }
  }

  return $affected_nodes;
}

/**
 * Implements function hook_exit().
 */
function dt_core_exit() {
  if (empty($GLOBALS['dt_core_nodes_to_update_alias']) || !is_array($GLOBALS['dt_core_nodes_to_update_alias'])) {
    return;
  }

  $nids_to_update = $GLOBALS['dt_core_nodes_to_update_alias'];
  $GLOBALS['dt_core_nodes_to_update_alias'] = array();
  foreach ($nids_to_update as $nid => $relatives) {
    // Paths update using the update method of the pathauto module.
    // Doing it one by one instead of using
    // pathauto_node_update_alias_multiple() to keep the order of items intact.
    foreach ($relatives as $rel_nid) {
      $node = node_load($rel_nid);
      pathauto_node_update_alias($node, 'update');
    }
  }
}

/**
 * Implements hook_pathauto_alias_alter().
 */
function dt_core_pathauto_alias_alter(&$alias, array &$context) {
  // Remove duplicates that are a result of a prefix defined in th URL pattern.
  // before the parent fields slug.
  //
  // For example:
  // The pattern "prefix/[parent:url]/[title]" might result in an alias like
  // "prefix/prefix/parent-title/title" if parent is of the same type since the
  // prefix is added twice. We will remove the duplicate prefix now.
  // We consider everything before the first token a prefix.
  $pattern_prefix = explode('[', $context['pattern']);
  $prefix = $pattern_prefix[0];

  if (!empty($prefix)) {
    // Check if it is subject of parent field.
    foreach ($GLOBALS['dt_core_parent_fields'] as $field_name) {
      // If the URL pattern does rely on this field remove duplicate prefix.
      if (_dt_core_parent_field_in_pattern($field_name, $context['pattern'])) {
        $alias = str_replace($prefix . $prefix, $prefix, $alias);
      }
    }
  }
}

/**
 * Checks if a URL pattern is relying on a parent field.
 *
 * @param string $field_name
 *   Field name.
 *
 * @return mixed
 *   string pattern token segment | bool FALSE
 */
function _dt_core_parent_field_in_pattern($field_name, $pattern) {
  // Check if URL pattern uses parent's URL.
  $pattern_segment = 'node:' . str_replace('_', '-', $field_name) . ':url:path';
  if (preg_match('/' . $pattern_segment . '/', $pattern)) {

    return $pattern_segment;
  }

  return FALSE;
}

/**
 * Implements hook_node_validate().
 */
function dt_core_node_validate($node, $form, &$form_state) {
  $wrapper = entity_metadata_wrapper('node', $node);
  foreach ($GLOBALS['dt_core_parent_fields'] as $field_name) {
    if (isset($wrapper->{$field_name}) && $parent = $wrapper->{$field_name}->value()) {
      // Detect if node has been set as its own parent.
      if ($parent->nid == $node->nid) {
        form_set_error($field_name, t('The page cannot be its own parent!'));
      }
      // Detect circular reference between two nodes.
      if (_dt_core_detect_circular_reference($node)) {
        form_set_error($field_name, t('There is a circular reference between this page and one of its parent!'));
      }
    }
  }
}

/**
 * Checks if a URL pattern is relying on a parent field.
 *
 * @param object $node
 *   Node.
 *
 * @return bool
 *   There is a circular reference between the two nodes.
 */
function _dt_core_detect_circular_reference($node) {
  $relatives = array();
  try {
    foreach ($GLOBALS['dt_core_parent_fields'] as $field_name) {
      $relatives += _dt_core_node_get_relatives($node->nid, $field_name, $direction = 'parents');
    }
  }
  catch (DTCoreParentCircular $e) {
    return TRUE;
  }

  return FALSE;
}

/**
 * Helper function for creating a taxonomy term in a vocabulary.
 *
 * @param string $vocabulary_machine_name
 *   Vocabulary machine name.
 * @param string $term_name
 *   Added term.
 *
 * @return bool
 *   Return TRUE if the taxonomy term was created.
 */
function _dt_core_create_taxonomy_term($vocabulary_machine_name, $term_name) {
  // Check the vocabulary if exist.
  if ($vocabulary = taxonomy_vocabulary_machine_name_load($vocabulary_machine_name)) {
    // Creating term.
    $term = array();
    $term['vocabulary_machine_name'] = $vocabulary_machine_name;
    $term['vid'] = $vocabulary->vid;
    $term['name'] = $term_name;
    // Save term as an entity.
    $entity = entity_create('taxonomy_term', $term);
    return entity_save('taxonomy_term', $entity);
  }
  return FALSE;
}

/**
 * Migrate existing field content from language "undefined" to entity language.
 *
 * @param string $field_name
 *   Field to enable entity translation on.
 */
function _dt_core_enable_entity_translation($field_name, &$sandbox) {
  $context = array('sandbox' => &$sandbox);
  module_load_include('inc', 'entity_translation', 'entity_translation.admin');
  entity_translation_translatable_switch(TRUE, $field_name);
  entity_translation_translatable_batch(TRUE, $field_name, TRUE, $context);
  $sandbox['#finished'] = $context['finished'];
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function dt_core_form_locale_languages_overview_form_alter(&$form, &$form_state) {
  // Increase the range of weights that can be assigned to languages in the
  // languages overview form. By default the languages can only be sorted using
  // the range -10 to +10 but since we have 24 languages this is not sufficient.
  foreach (element_children($form['weight']) as $key) {
    $form['weight'][$key]['#delta'] = 20;
  }
}

/**
 * Helper function to enable languages.
 *
 * @param array $languages
 *   Language codes of languages to be enabled.
 */
function _dt_core_enable_lanugages($languages = array()) {
  module_load_include('inc', 'locale', 'locale.admin');
  $form_state = array();
  foreach ($languages as $key => $langcode) {
    // Enable language.
    multisite_config_service('locale')->addLanguage($langcode);
    // Set the appropriate weight for languages to follow the order defined in
    // the array.
    $form_state['values']['weight'][$langcode] = -20 + $key;

    // Portuguese exception:
    // In Drupal the "pt" prefix belongs to Portuguese / International but we
    // need Portuguese / Portugal to have this prefix (theme_image_style has
    // "pt-pt" as default prefix). We need to change this to "pt".
    if ($langcode == 'pt-pt') {
      db_update('languages')
        ->fields(array(
          'name' => 'Portuguese',
          'prefix' => 'pt',
        ))
        ->condition('language', $langcode)
        ->execute();
    }
  }
  // Save the order through the original form.
  drupal_form_submit('locale_languages_overview_form', $form_state);
  // Enable URL suffix based language negotiation.
  multisite_config_service('locale')->setLanguageNegotiation('nexteuropa_multilingual_url_suffix');
  // Fix lowercase languages.
  _dt_core_transform_language_to_lower_case(_dt_core_lower_case_languages());
}

/**
 * Implements hook_node_presave().
 *
 * If a whitespace has been entered after a title, we remove it.
 */
function dt_core_node_presave($node) {
  $node->title = rtrim($node->title);

  // Handle the header background image.
  if (isset($node->field_core_header_image) && isset($node->nid)) {
    // We want to store those css files in a specific path.
    $dir = 'public://css/header-backgrounds/';
    // Prepare the filesystem.
    file_prepare_directory($dir, FILE_CREATE_DIRECTORY);
    // Build the uri for our css file.
    $uri = $dir . 'header_background_node_' . $node->nid . '.css';
    // Get the real path basing on the uri.
    $filepath = drupal_realpath($uri);
    // Check if the file exists.
    $existing  = file_get_contents($filepath);
    // Check if there is an image.
    $header_back = isset($node->field_core_header_image['und'][0]['fid']);

    // Remove the css if one is found but the field is empty.
    if (!$header_back && $existing) {
      unlink($filepath);
    }

    // Without breakpoints this would not make much sense.
    elseif ($header_back && module_exists('breakpoints')) {
      // We need the file uri.
      $file = file_load($node->field_core_header_image['und'][0]['fid']);
      // Get all the breakpoints belonging to "this" theme.
      $breakpoints = breakpoints_breakpoint_load_all_theme('europa');
      // Need to reverse the order of the breakpoint, mobile first.
      $breakpoints = array_reverse($breakpoints);
      // Get all the images presets.
      $styles = image_styles();
      // Get the presets name.
      $style_names = array_keys($styles);
      // Filter the ones regarding the header image.
      $header_styles = preg_grep('#^header_image*#', $style_names);
      // Prepare containers.
      $mapping = array();
      $css = '';

      foreach ($breakpoints as $breakpoint) {
        $name = $breakpoint->machine_name;
        // Get the key to find correspondencies in the image presets.
        $breakpoint_key = substr($name, strrpos($name, '.') + 1);
        // Get the styles related to this breakpoint.
        $style_names_breakpoint = preg_grep('#' . $breakpoint_key . '#', $header_styles);
        if (!empty($style_names_breakpoint)) {
          // We base on the multiplier.
          sort($style_names_breakpoint);
          foreach ($style_names_breakpoint as $style_name) {
            // Build an array mapping the breakpoints media queries and the
            // image url.
            $mapping[$breakpoints[$name]->breakpoint][] = image_style_url($style_name, $file->uri);
          }
        }
        // Create the css rules for each breakpoint.
        $css .= '@media ' . $breakpoints[$name]->breakpoint . ' {' . PHP_EOL;
        $css .= ' .page-header--image {' . PHP_EOL;
        $css .= '   background-image: url("' . $mapping[$breakpoints[$name]->breakpoint][0] . '");' . PHP_EOL;
        $css .= ' }' . PHP_EOL;
        $css .= '}' . PHP_EOL;
        $css .= PHP_EOL;

        // High resolution displays.
        $css .= '@media ' . $breakpoints[$name]->breakpoint . ', (-webkit-min-device-pixel-ratio: 2), (min--moz-device-pixel-ratio: 2), (-o-min-device-pixel-ratio: 2/1), (min-device-pixel-ratio: 2),(min-resolution: 2dppx)  {' . PHP_EOL;
        $css .= ' .page-header--image {' . PHP_EOL;
        $css .= '   background-image: url("' . $mapping[$breakpoints[$name]->breakpoint][1] . '");' . PHP_EOL;
        $css .= ' }' . PHP_EOL;
        $css .= '}' . PHP_EOL;
        $css .= PHP_EOL;
      }

      // Act only if something has been changed or if the file doesn't exist
      // yet.
      if ($existing != $css) {
        file_unmanaged_save_data($css, $uri, FILE_EXISTS_REPLACE);
      }
    }
  }
}

/**
 * Implements hook_preprocess_page().
 */
function dt_core_preprocess_page(&$variables) {
  $node = &$variables['node'];
  // Handle the header background image.
  if (isset($node) && isset($node->field_core_header_image)) {
    $header_back = field_get_items('node', $node, 'field_core_header_image');
    if ($header_back) {
      // Set a variable available in the tpls.
      $variables['node']->header_back = TRUE;
      $dir = 'public://css/header-backgrounds/';
      // Add the css to the page.
      $uri = $dir . 'header_background_node_' . $node->nid . '.css';
      drupal_add_css($uri, array('group' => CSS_THEME, 'every_page' => FALSE));
    }
  }
}

/**
 * Implements hook_context_load_alter().
 */
function dt_core_context_load_alter(&$context) {
  if ($context->name == 'dt_core_non_homepage_pages') {
    if ($node = menu_get_object('node')) {
      global $language;
      $interface_language = $language->language;
      $content_languages = $node->translations->data;

      if (array_key_exists($interface_language, $content_languages)) {
        unset($context->reactions['block']['blocks']['language_selector_page-language_selector_page']);
      }
    }
  }
}

/**
 * Removes maxlength configuration from field.
 */
function _dt_core_disable_maxlength($element) {
  // Check if we are translating and maxlength for field is enabled.
  if (isset($element['#field_name']) && isset($element['#maxlength']) && isset($element['#language']) &&  isset($element['#entity']) && isset($element['#entity']->language) && $element['#language'] !== $element['#entity']->language) {
    // Remove maxlength.
    unset($element['#maxlength']);
  }

  return $element;
}

/**
 * Implements hook_element_info_alter().
 */
function dt_core_element_info_alter(&$cache) {
  $cache['textarea']['#process'][] = '_dt_core_disable_maxlength';
  $cache['textfield']['#process'][] = '_dt_core_disable_maxlength';
}

/**
 * Helper function to return a list of languages that should be enabled.
 *
 * Languages that will be enabled. The order they need to appear when listed is
 * defined here:
 * @link http://publications.europa.eu/code/en/en-370200.htm.
 *
 * @return array
 *   List of languages.
 */
function _dt_core_ec_official_languages() {
  return array(
    'bg',
    'cs',
    'da',
    'de',
    'et',
    'el',
    'en',
    'es',
    'fr',
    'ga',
    'hr',
    'it',
    'lv',
    'lt',
    'hu',
    'mt',
    'nl',
    'pl',
    'pt-pt',
    'ro',
    'sk',
    'sl',
    'fi',
    'sv',
  );
}

/**
 * Helper function to return a list of languages that need to be lower case.
 *
 * @return array
 *   List of languages that need to be lower case.
 */
function _dt_core_lower_case_languages() {
  return array(
    'bg',
    'cs',
    'da',
    'et',
    'el',
    'es',
    'fr',
    'hr',
    'lv',
    'lt',
    'hu',
    'pl',
    'pt-pt',
    'ro',
    'sk',
    'sl',
    'fi',
    'sv',
  );
}

/**
 * Helper function to transform language names to lower case.
 *
 * @param array $language_codes
 *   List of language codes.
 *
 * @return bool
 *   TRUE/FALSE.
 */
function _dt_core_transform_language_to_lower_case(array $language_codes) {
  // Ininitialize our return value.
  $return = TRUE;

  // Loop the results and update the langcode.
  foreach ($language_codes as $langcode) {
    // Our update query, this either returns TRUE or FALSE.
    $query = db_update('languages')
      ->expression('native', 'LCASE(native)')
      ->condition('language', $langcode)
      ->execute();

    // If there were no issues, we show a message that everything went well. In
    // other cases notifiy about the error, and make the function return FALSE.
    if ($query) {
      // Create our log message.
      $watchdog_content = array(
        'message' => 'Language %langcode updated to lower case.',
        'type' => WATCHDOG_INFO,
        'replacement' => array('%langcode' => $langcode),
      );
    }
    else {
      // Create our log message.
      $watchdog_content = array(
        'message' => 'Could not update language %langcode to lower case. This might come due to the fact the language is not yet available or it already is updated.',
        'type' => WATCHDOG_WARNING,
        'replacement' => array('%langcode' => $langcode),
      );
      // We had one error, but we can finish other querys. Set our return
      // parameter to false, so that we can continue the query and return false
      // afterwards.
      $return = FALSE;
    }

    // Watchdog our log message.
    watchdog('dt_core', $watchdog_content['message'], $watchdog_content['replacement'], $watchdog_content['type']);
  }

  // Retrun our outcome.
  return $return;
}

/**
 * Implements hook_views_query_alter().
 *
 * To avoid reconfiguring our views we simply remove our sort field from the
 * query. This query alteration, takes in consideration that we have a maximum
 * of 3 possible languages. It joins the translated data.
 */
function dt_core_views_query_alter(&$view, &$query) {
  // If it is one of our listings.
  if (isset($view->sort['title_field_value'])) {
    // Get our languages.
    $fallback_languages = _dt_core_content_language_order();
    // Sort direction from our sort.
    $sort_direction = 'ASC';

    // If the sort direction is set we use the set one.
    if (isset($view->sort['title_field_value']->options['order'])) {
      $sort_direction = $view->sort['title_field_value']->options['order'];
    }

    // Language subquerys.
    $or = db_or();

    // Also we can add our sorting function here. So lets start with the
    // ininitialization of that variable.
    $order_by_case = 'CASE ';
    // Add these languages to the query.
    foreach ($fallback_languages as $key => $fallback_language) {
      $or->condition('title_field.language', $fallback_language);
      $order_by_case .= 'WHEN title_field.language = \'' . $fallback_language . '\' THEN ' . $key . ' ';
    }
    $order_by_case .= 'END';

    // Build our sub query.
    $sub_query = db_select('field_data_title_field', 'title_field');
    $sub_query->addField('title_field', 'title_field_value', 'translated_title');
    $sub_query->addField('title_field', 'entity_id', 'translated_id');
    $sub_query->addField('title_field', 'language');
    $sub_query->addExpression($order_by_case);
    $sub_query->condition($or);

    // Create new join object.
    $join = new views_join();
    $join->definition = array(
      'table formula' => $sub_query,
      'left_field' => 'nid',
      'field' => 'translated_id',
      'left_table' => 'node',
    );
    $join->left_table = 'node';
    $join->field = 'translated_id';
    $join->left_field = 'nid';
    $join->type = 'LEFT';
    // This will make sure that we only use the first and best translation
    // match. Because the order by case is the same, a simple string replace is
    // enough to make it work.
    $join->extra = 'title_field.expression = (SELECT Min(' . str_replace('title_field.language', 'language', $order_by_case) . ') FROM field_data_title_field WHERE entity_id = title_field.translated_id)';

    // Do the actual join.
    $query->table_queue['title_field'] = array(
      'alias' => 'title_field',
      'table' => $sub_query,
      'relationship' => 'node',
      'join' => $join,
    );

    // Replace the title sort fields with our custom.
    foreach ($query->orderby as $key => &$value) {
      if ($value['field'] == 'field_data_title_field_title_field_value') {
        $value['field'] = 'title_field.translated_title';
        break;
      }
    }

    // This is originally coming from our sort, we could even delete this part
    // once we move to a better solution. As we replace the sorting logic, we
    // have to unset these, as they are causing the duplicate results.
    if (isset($query->table_queue['field_data_title_field'])) {
      unset($query->table_queue['field_data_title_field']);
    }
    // Remove the field.
    if (isset($query->fields['field_data_title_field_title_field_value'])) {
      unset($query->fields['field_data_title_field_title_field_value']);
    }
  }
}

/**
 * Get the languages that are applicable in the right order of fallback.
 */
function _dt_core_content_language_order() {
  global $language;
  // Get the first few languages of our fallback array. If we have a 2nd
  // language parameter set, we have to work with an additional language. If
  // not, we only need one.
  // Set our maximum languages to check.
  $max_languages = 1;
  // First we get our url parameters.
  $parameters = drupal_get_query_parameters();
  // Check if the 2nd-language parameter is set.
  if (isset($parameters['2nd-language']) && $parameters['2nd-language'] !== 'en') {
    $max_languages = 2;
  }
  // Get the maximum extra languages.
  $fallback_languages = array_slice(language_fallback_get_candidates(), 0, $max_languages);
  // Add our current site language to the array.
  if (!in_array($language->language, $fallback_languages)) {
    array_unshift($fallback_languages, $language->language);
  }
  else {
    // Our default language is in the array but might not be the first. So we
    // move it.
    // Get the key of the language.
    $main_language_key = array_search($language->language, $fallback_languages);
    // Store it temporary.
    $prepend_language = $fallback_languages[$main_language_key];
    // Remove the item.
    unset($fallback_languages[$main_language_key]);
    // Then add it to the front.
    array_unshift($fallback_languages, $prepend_language);
  }

  return $fallback_languages;
}

/**
 * Helper function to get plurial names.
 *
 * This should move to the dt_node_settings module.
 *
 * @param string $bundle
 *   The name of the bundle to get the plurial name.
 */
function _dt_core_get_plurial_content_types($bundle) {
  // Forming plurals for existing content types.
  $plurals = array(
    'announcement' => t("announcements"),
    'page' => t("pages"),
    'contact' => t("contacts"),
    'department' => t("departments"),
    'editorial_team' => t("editorial teams"),
    'file' => t("files"),
    'basic_page' => t("pages"),
    'person' => t("people"),
    'policy' => t("policies"),
    'policy_area' => t("policy areas"),
    'policy_implementation' => t("policy implementations"),
    'policy_input' => t("policy inputs"),
    'policy_keyfile' => t("policy key files"),
    'priority' => t("priorities"),
    'publication' => t("publications"),
    'class' => t("classes"),
    'topic' => t("topics"),
    'toplink' => t("top links"),
  );

  $singular = node_type_get_name($bundle);
  // If user preference for plural form - use it, otherwise use the label.
  if (isset($plurals[$bundle])) {
    $plural = $plurals[$bundle];
  }
  else {
    $plural = strtolower(t("@bundles", array('@bundle' => $singular)));
  }

  $forms = array(
    'singular' => strtolower($singular),
    'plural' => $plural,
  );

  return $forms;
}

/**
 * Implements hook_preprocess_views_view().
 *
 * This was in the informational template before. But moved it here because we
 * need it on multiple templates that use dt_core.
 */
function dt_core_preprocess_views_view(&$variables) {
  $view = $variables['view'];

  $content_type = array();
  $content_type_filters = $view->filter['type']->value;
  foreach ($content_type_filters as $filter) {
    $content_type = $filter;
  }

  $variables['items_count'] = '';

  if ((in_array('listing', $variables['classes_array'])) || $view->style_plugin->plugin_name == 'nexteuropa_bem_listing' && isset($view->exposed_data)) {
    // Calculate the number of items displayed in a view listing.
    $total_rows = !$view->total_rows ? count($view->result) : $view->total_rows;

    $content_type_forms = _dt_core_get_plurial_content_types($content_type);

    if ($total_rows == 0) {
      $items_count = t("No @items", array('@items' => $content_type_forms['plural']));
    }
    else {
      $items_count = $total_rows . ' ' .
        format_plural($total_rows, $content_type_forms['singular'], $content_type_forms['plural']);
    }

    $variables['items_count'] = $items_count;
  }
}
