<?php
/**
 * @file
 * Code for the Department feature.
 */

include_once 'dt_department.features.inc';

/**
 * Implements hook_migrate_api().
 */
function dt_department_migrate_api() {
  return array(
    'api' => 2,
    'groups' => array(
      'NextEuropa' => array(
        'title' => t('Stage initial content, department tasks.'),
      ),
    ),
    'migrations' => array(
      'DTDepartmentTasks' => array(
        'class_name' => 'DTDepartmentTasksMigration',
        'group_name' => 'NextEuropa Digital Transformation',
      ),
    ),
  );
}
