<?php
/**
 * @file
 * DT Policy input install file.
 */

/**
 * Implements hook_install().
 */
function dt_STARTERKIT_DEFAULT_install() {
  $t = get_t();
  drupal_set_message($t('NextEuropa STARTERKIT_CONTENT_NAME feature is installed on your site.'));
}

/**
 * Implements hook_uninstall().
 */
function dt_STARTERKIT_DEFAULT_uninstall() {
	$t = get_t();
  drupal_set_message($t('NextEuropa STARTERKIT_CONTENT_NAME feature is uninstalled on your site.'));
}
