<?php
/**
 * @file
 * Default feature.
 */

include_once 'dt_commemorative_coins_default.features.inc';

/**
 * Implements hook_date_select_process_alter().
 */
function dt_commemorative_coins_default_date_select_process_alter(&$element, &$form_state, $context) {
  if ($context['form']['#id'] == 'views-exposed-form-commemorative-coins-page') {
    if (isset($element['year']['#options']['']) && $element['year']['#options'][''] == '-Year') {
      $element['year']['#options'][''] = t('- Any -');
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function dt_commemorative_coins_default_form_commemorative_coins_node_form_alter(&$form, &$form_state, $form_id) {
  $form['#validate'] = ['_dt_commemorative_coins_validate'];
}

/**
 * Custom validation for the commemorative coins.
 *
 * @param array $form
 *   The form array.
 * @param array $form_state
 *   The form state array.
 */
function _dt_commemorative_coins_validate(&$form, &$form_state) {
  if (!is_numeric($form_state['values']['field_cc_issuing_volumes'][LANGUAGE_NONE][0]['value'])) {
    form_set_error('error', t('The field Issuing volume has to contain only numbers.'));
  }
}
