<?php
/**
 * @file
 * Code for the DT Contact feature.
 */

include_once 'dt_contact.features.inc';

/**
 * Implements hook_node_view().
 */
function dt_contact_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'contact' && ($view_mode == 'teaser' || $view_mode == 'full')) {
    // Check if field_contact_phone_number have a value,
    // we will hide it if empty.
    $field = 'field_contact_phone_number';
    $info = field_info_field($field);
    $function = $info['module'] . '_field_is_empty';
    if (function_exists($function)) {
      $telf = field_get_items('node', $node, $field);
      $telf_empty = $function($telf, $info);
      if (!$telf_empty) {
        unset($node->$field);
      }
    }

    // Check if the address thorouhfare and premise have a value
    // hide these fields if they don't.
    $field = 'field_contact_postal_mail';
    $value = field_get_items('node', $node, $field);
    if (isset($value)) {
      if (!($value[0]['thoroughfare']) && !($value[0]['premise'])) {
        unset($node->$field);
      }
    }
    else {
      unset($node->$field);
    }
  }
}


/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Extra validate callback specific for
 * telephone numbers field.
 */
function dt_contact_form_contact_node_form_alter(&$form, &$form_state, $form_id) {
  // Add extra validation.
  $form['#validate'][] = '_dt_contact_phone';
}

/**
 * Callback handler for phone field validation.
 */
function _dt_contact_phone($form, &$form_state) {
  $lang = $form['field_contact_phone_number']['#language'];
  if ($form_state['values']['field_contact_phone_number'][$lang][0]['value']) {
    $contact_phone = $form_state['values']['field_contact_phone_number'][$lang][0]['value'];
    // Validate the current phone number.
    foreach (_dt_core_contactphone_patterns() as $pattern => $pattern_values) {
      preg_match($pattern_values['pattern'], $contact_phone, $matches);
      if (!isset($matches[$pattern_values['return_key']]) && isset($pattern_values['required'])) {
        form_set_error('field_contact_phone_number', $pattern_values['explain']);
      }
    }
  }
}
