VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/precise64"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.hostname = "contentcluster"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 9000, host: 9001
  # config.vm.network "forwarded_port", guest: 53, host: 53
  config.vm.synced_folder "www/", "/var/www"
  config.vm.synced_folder "bin/", "/home/vagrant/bin"
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
  end
end

