<?php
/**
 * @file
 * Code for the Person feature.
 */

include_once 'dt_person.features.inc';

/**
 * Implements hook_migrate_api().
 */
function dt_person_migrate_api() {
  return array(
    'api' => 2,
    'groups' => array(
      'NextEuropa' => array(
        'title' => t('Including taxonomy terms in the Person roles vocabulary.'),
      ),
    ),
    'migrations' => array(
      'DTPersonRolesMigrator' => array(
        'class_name' => 'DTPersonRolesMigration',
        'group_name' => 'NextEuropa Digital Transformation',
      ),
    ),
  );
}

/**
 * Implements hook_field_attach_view_alter().
 *
 * This wil alter the output of the context nav when its a person.
 */
function dt_person_field_attach_view_alter(&$output, $context) {
  // Append RDF term mappings on displayed taxonomy links.
  foreach (element_children($output) as $field_name) {
    $element = &$output[$field_name];
    if ($element['#field_type'] == 'entityreference' && $element['#field_name'] == 'field_core_persons' && $element['#formatter'] == 'context_nav_item') {

      // Set our special load variable to FALSE by default. As these labels
      // can be different we need to maybe replace the default title view with
      // amore specific view mode. For more information about these
      // customizations:
      // @see: https://webgate.ec.europa.eu/CITnet/jira/browse/NEXTEUROPA-4789
      $load_person_name_view = FALSE;

      if (count($element['#items']) > 1) {
        // Set our check default to true.
        $same_title = TRUE;
        // Check if title are different.
        foreach ($element['#items'] as $item) {
          // Load entity_metadata_wrapper.
          $check_entity = entity_metadata_wrapper('node', $item['entity']);
          // Check if the tid is the same. If so, we continue. If not, stop the
          // loop and set same_title to false.
          if (isset($last_title_tid) && $last_title_tid !== $check_entity->field_person_role->value()->tid) {
            $same_title = FALSE;
            break;
          }
          // Save the last id we checked.
          $last_title_tid = $check_entity->field_person_role->value()->tid;
        }
        // If after our full loop the title is still the same, we can safely set
        // our title.
        if ($same_title && isset($check_entity->field_person_role)) {
          $wrapper_label = $check_entity->field_person_role->value()->name;
          // Tell our formatter to use the name display mode.
          $load_person_name_view = TRUE;
        }
      }
      elseif (isset($element['#items'][0]) && isset($element['#items'][0]['entity'])) {
        // If it is just one person. Use the first. But double check if for a
        // value.
        $check_entity = entity_metadata_wrapper('node', $element['#items'][0]['entity']);
        if (isset($check_entity->field_person_role)) {
          $wrapper_label = $check_entity->field_person_role->value()->name;
          // Tell our formatter to use the name display mode.
          $load_person_name_view = TRUE;
        }
      }
      else {
        $load_person_name_view = FALSE;
      }

      // Only start looping on a specific display.
      if ($load_person_name_view) {
        // Now that we know wether or not we should display specific information
        // we can alter the display.
        foreach ($element['#items'] as $key => $item) {
          // If we need an alternative display.
          if ($person_render = entity_view('node', array($item['entity']), 'name')) {
            // Return our element.
            $element[$key]['#markup'] = render($person_render);
          }
        }

        // Alter our label if we have one.
        if (isset($wrapper_label)) {
          // Call our custom helper to get our prefix and suffix.
          $wrapper = _nexteuropa_formatters_get_context_nav_wrapper($wrapper_label);

          // Apply it to the elemen.
          $element['#prefix'] = $wrapper['prefix'];
          $element['#suffix'] = $wrapper['suffix'];
        }
      }
    }
  }
}
