<?php
/**
 * @file
 * Code for the Core feature.
 */

include_once 'dt_core.features.inc';

/**
 * Implements hook_field_widget_form_alter().
 */
function dt_core_field_widget_form_alter(&$element, &$form_state, $context) {
  if ($context['field']['type'] == 'entityreference') {
    if ($context['field']['settings']['target_type'] == 'node' && !empty($context['field']['settings']['handler_settings']['target_bundles'])) {
      $types = $context['field']['settings']['handler_settings']['target_bundles'];
      $types_count = count($types);
      $links = '';
      $i = 0;
      $separator = ',';
      foreach ($types as $machine_name) {
        $type = node_type_get_type($machine_name);
        $current_separator = $types_count > 1 && $i == $types_count - 2 ? ' ' . t('or') : $separator;
        $links .= l($type->name, 'node/add/' . $machine_name, array('attributes' => array('target' => '_blank'))) . $current_separator . ' ';
        $i++;
      }
      $links = rtrim($links, $separator . ' ');
      $description = '<p>' . t('In case the content you try to refer to does not exist yet you can create it by going to !links.', array('!links' => $links)) . '</p>';
      if (isset($element['target_id'])) {
        $element['target_id']['#description'] = $description . $element['target_id']['#description'];
      }
      else {
        $element['#description'] = $description . $element['#description'];
      }
    }
  }
}

/**
 * Implements hook_block_info().
 */
function dt_core_block_info() {
  $blocks['dt_block_copyright'] = array(
    'info' => t('Copyright paragraph'),
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );

  return $blocks;
}

/**
 * Implements hook_block_configure().
 */
function dt_core_block_configure($delta = '') {
  $form = array();
  if ($delta == 'dt_block_copyright') {
    $form['copyright_paragraph'] = array(
      '#type' => 'textfield',
      '#title' => t('Copyright statement'),
      '#size' => 60,
      '#description' => t('Contains the copyright statement for the website shown in the footer.'),
      '#default_value' => variable_get('copyright_paragraph', t('© European Commission copyright.')),
    );
  }
  return $form;
}

/**
 * Implements hook_block_save().
 */
function dt_core_block_save($delta = '', $edit = array()) {
  if ($delta == 'dt_block_copyright') {
    variable_set('copyright_paragraph', $edit['copyright_paragraph']);
  }
}

/**
 * Implements hook_block_view().
 */
function dt_core_block_view($delta = '') {
  switch ($delta) {
    case 'dt_block_copyright':
      $block['subject'] = "";
      $block['content'] = dt_core_get_blocks_content($delta);
      break;
  }
  return $block;
}

/**
 * A module-defined block content function.
 */
function dt_core_get_blocks_content($which_block) {
  switch ($which_block) {
    case 'dt_block_copyright':
      $result = array(
        '#prefix' => "<div class='footer__disclaimer'>",
        '#suffix' => "</div>",
        '#markup' => variable_get('copyright_paragraph',
          t("© European Commission copyright.")
        ),
      );
      return $result;
  }
}
