<?php

/**
 * @file
 * Show 404 pages on helper content types.
 */

/**
 * Implements hook_page_alter().
 *
 * We use this because it is only called once per request.
 */
function dt_helper_404_page_alter(&$page) {
  // Get the node we are about to display.
  if ($node = menu_get_object('node')) {
    // Check if it is in the helper list.
    if (_dt_helper_404_is_helper($node->type)) {
      // Redirect to the 404 page.
      drupal_goto(MENU_NOT_FOUND);
    }
  }
}

/**
 * Helper function to return all disabled node types.
 *
 * This has been defined as a seperate function so that it's easy to move to a
 * configuration page.
 */
function _dt_helper_404_is_helper($node_type) {
  // Build a list of helper content types. We could move this to a setting.
  // basic_page cannot be here, as it is our 404page. (loop).
  $helper_types = array(
    'article',
    'banner_quote',
    'banner_video',
    'class_link_group',
    'featured_item',
    'policy_implementation',
    'policy_input',
    'policy_keyfile',
    'publication',
    'toplink',
    'editorial_team',
    'file',
  );

  // If our node type is in, we return true.
  if (in_array($node_type, $helper_types)) {
    return TRUE;
  }

  // In all other cases we return false.
  return FALSE;
}
