<?php

/**
 * @file
 * DT Page install file.
 */

/**
 * Implements hook_install().
 */
function dt_page_default_install() {
  $t = get_t();
  drupal_set_message($t('NextEuropa Page Default feature is installed on your site.'));
}

/**
 * Implements hook_uninstall().
 */
function dt_page_default_uninstall() {
  drupal_set_message(t('NextEuropa Page Default feature is uninstalled on your site.'));
}
