<?php
$permissions['administrator'] = array(
  'accept translation jobs',
  'access administration menu',
  'access administration pages',
  'access all views',
  'access bean overview',
  'access broken links report',
  'access ckeditor link',
  'access coffee',
  'access comments',
  'access content',
  'access content overview',
  'access contextual links',
  'access helper content types',
  'access media browser',
  'access own broken links report',
  'access PDF version',
  'access print',
  'access rules debug',
  'access send by email',
  'access site in maintenance mode',
  'access site reports',
  'access site-wide contact form',
  'access user contact forms',
  'access user profiles',
  'access workbench',
  'add media from remote sources',
  'administer actions',
  'administer bean settings',
  'administer bean types',
  'administer beans',
  'administer blocks',
  'administer breakpoints',
  'administer CAPTCHA settings',
  'administer chr',
  'administer ckeditor link',
  'administer coffee',
  'administer comments',
  'administer contact forms',
  'administer content translations',
  'administer content types',
  'administer contexts',
  'administer css injection',
  'administer custom formatters',
  'administer dt_social_network_links',
  'administer easy_breadcrumb',
  'administer ecas',
  'administer entity translation',
  'administer facets',
  'administer feature sets',
  'administer fieldgroups',
  'administer file types',
  'administer files',
  'administer filters',
  'administer flags',
  'administer group',
  'administer image styles',
  'administer js_injector',
  'administer languages',
  'administer linkchecker',
  'administer media browser',
  'administer media wysiwyg view mode',
  'administer menu',
  'administer menu attributes',
  'administer menu_token',
  'administer meta tags',
  'administer nodes',
  'administer password policy',
  'administer pathauto',
  'administer permissions',
  'administer pictures',
  'administer print',
  'administer quicktabs',
  'administer realname',
  'administer rules',
  'administer scheduler',
  'administer search',
  'administer site configuration',
  'administer splash screen',
  'administer taxonomy',
  'administer taxonomy_browser',
  'administer themes',
  'administer tmgmt',
  'administer translation tasks',
  'administer url aliases',
  'administer users',
  'administer uuid',
  'administer video presets',
  'administer views',
  'administer voting api',
  'administer workbench',
  'administer workbench moderation',
  'admin_classes',
  'admin_display_suite',
  'admin_fields',
  'admin_view_modes',
  'advanced migration information',
  'assign node weight',
  'block IP addresses',
  'bypass conversion video',
  'bypass file access',
  'bypass node access',
  'bypass rules access',
  'bypass workbench moderation',
  'cancel account',
  'change own username',
  'ckeditor_lite highlight changes',
  'configure helper content types',
  'context ajax block access',
  'convert on submission',
  'create announcement content',
  'create article content',
  'create files',
  'create page content',
  'create translation jobs',
  'create url aliases',
  'delete any announcement content',
  'delete any article content',
  'delete any audio files',
  'delete any document files',
  'delete any image files',
  'delete any page content',
  'delete any video files',
  'delete own announcement content',
  'delete own article content',
  'delete own audio files',
  'delete own document files',
  'delete own image files',
  'delete own page content',
  'delete own video files',
  'delete revisions',
  'delete terms in 1',
  'delete terms in 2',
  'display drupal links',
  'download any audio files',
  'download any document files',
  'download any image files',
  'download any video files',
  'download own audio files',
  'download own document files',
  'download own image files',
  'download own video files',
  'edit any announcement content',
  'edit any article content',
  'edit any audio files',
  'edit any document files',
  'edit any image files',
  'edit any page content',
  'edit any video files',
  'edit bean view mode',
  'edit link settings',
  'edit meta tags',
  'edit own announcement content',
  'edit own article content',
  'edit own audio files',
  'edit own comments',
  'edit own document files',
  'edit own image files',
  'edit own page content',
  'edit own video files',
  'edit terms in 1',
  'edit terms in 2',
  'export nodes',
  'export own nodes',
  'flush caches',
  'generate features',
  'migration information',
  'moderate content from draft to needs_review',
  'moderate content from needs_review to draft',
  'moderate content from needs_review to published',
  'moderate content from needs_review to validated',
  'moderate content from published to archived',
  'moderate content from validated to published',
  'multisite_workbench_moderation_view_bulk_update',
  'node-specific print configuration',
  'notify of path changes',
  'override default scheduler time',
  'override player dimensions',
  'post comments',
  'provide translation services',
  're convert video',
  'rename features',
  'revert revisions',
  'schedule (un)publishing of nodes',
  'search content',
  'select account cancellation method',
  'send unlimited emails',
  'show format selection for bean',
  'show format selection for comment',
  'show format selection for file',
  'show format selection for flagging',
  'show format selection for node',
  'show format selection for og_membership',
  'show format selection for og_membership_type',
  'show format selection for rules_config',
  'show format selection for taxonomy_term',
  'show format selection for user',
  'show format tips',
  'show more format tips link',
  'skip CAPTCHA',
  'skip comment approval',
  'submit translation jobs',
  'toggle field translatability',
  'translate admin strings',
  'translate any entity',
  'translate content',
  'translate interface',
  'translate node entities',
  'translate user-defined strings',
  'use advanced search',
  'use ctools import',
  'use default thumb',
  'use flag import',
  'use media wysiwyg',
  'use PHP for label patterns',
  'use text format basic_html',
  'use text format filtered_html',
  'use text format full_html',
  'use workbench_moderation my drafts tab',
  'use workbench_moderation needs review tab',
  'version management edits',
  'view advanced help index',
  'view advanced help popup',
  'view advanced help topic',
  'view all unpublished content',
  'view bean page',
  'view bean revisions',
  'view files',
  'view moderation history',
  'view moderation messages',
  'view own files',
  'view own private files',
  'view own unpublished content',
  'view private files',
  'view rate results page',
  'view revisions',
  'view scheduled content',
  'view the administration theme',
);
