<?php
$permissions['administrator'] = array(
  'accept translation jobs',
  'access administration menu',
  'access administration pages',
  'access all views',
  'access bean overview',
  'access broken links report',
  'access ckeditor link',
  'access coffee',
  'access comments',
  'access content',
  'access content overview',
  'access contextual links',
  'access ecas import users function',
  'access helper content types',
  'access media browser',
  'access own broken links report',
  'access PDF version',
  'access print',
  'access rules debug',
  'access send by email',
  'access site in maintenance mode',
  'access site reports',
  'access site-wide contact form',
  'Access to unpublished file',
  'access user contact forms',
  'access user profiles',
  'access workbench',
  'add media from remote sources',
  'administer actions',
  'administer bean settings',
  'administer bean types',
  'administer beans',
  'administer blocks',
  'administer breakpoints',
  'administer CAPTCHA settings',
  'administer chr',
  'administer ckeditor link',
  'administer coffee',
  'administer comments',
  'administer contact forms',
  'administer content translations',
  'administer content types',
  'administer contexts',
  'administer css injection',
  'administer custom formatters',
  'administer dt_social_network_links',
  'administer easy_breadcrumb',
  'administer ecas',
  'administer entity translation',
  'administer facets',
  'administer feature sets',
  'administer fieldgroups',
  'administer file types',
  'administer files',
  'administer filters',
  'administer flags',
  'administer group',
  'administer image styles',
  'administer js_injector',
  'administer languages',
  'administer linkchecker',
  'administer media browser',
  'administer media wysiwyg view mode',
  'administer menu',
  'administer menu attributes',
  'administer menu_token',
  'administer meta tags',
  'administer nodes',
  'administer password policy',
  'administer pathauto',
  'administer permissions',
  'administer pictures',
  'administer piwik',
  'administer print',
  'administer quicktabs',
  'administer realname',
  'administer rules',
  'administer scheduler',
  'administer search',
  'administer site configuration',
  'administer splash screen',
  'administer taxonomy',
  'administer taxonomy_browser',
  'administer themes',
  'administer tmgmt',
  'administer translation tasks',
  'administer url aliases',
  'administer users',
  'administer uuid',
  'administer video presets',
  'administer views',
  'administer voting api',
  'administer workbench',
  'administer workbench moderation',
  'admin_classes',
  'admin_display_suite',
  'admin_fields',
  'admin_view_modes',
  'advanced migration information',
  'assign node weight',
  'block IP addresses',
  'bypass conversion video',
  'bypass file access',
  'bypass node access',
  'bypass rules access',
  'bypass workbench moderation',
  'cancel account',
  'change own username',
  'ckeditor_lite highlight changes',
  'configure helper content types',
  'configure sweaver',
  'context ajax block access',
  'convert on submission',
  'create announcement content',
  'create any site_menu bean',
  'create basic_page content',
  'create class content',
  'create class_link_group content',
  'create contact content',
  'create department content',
  'create editorial_team content',
  'create file content',
  'create files',
  'create info_homepage content',
  'create page content',
  'create person content',
  'create policy content',
  'create policy_area content',
  'create policy_implementation content',
  'create policy_input content',
  'create policy_keyfile content',
  'create priority content',
  'create publication content',
  'create topic content',
  'create toplink content',
  'create translation jobs',
  'create url aliases',
  'delete any announcement content',
  'delete any audio files',
  'delete any basic_page content',
  'delete any class content',
  'delete any class_link_group content',
  'delete any contact content',
  'delete any department content',
  'delete any document files',
  'delete any editorial_team content',
  'delete any file content',
  'delete any image files',
  'delete any info_homepage content',
  'delete any page content',
  'delete any person content',
  'delete any policy content',
  'delete any policy_area content',
  'delete any policy_implementation content',
  'delete any policy_input content',
  'delete any policy_keyfile content',
  'delete any priority content',
  'delete any publication content',
  'delete any site_menu bean',
  'delete any topic content',
  'delete any toplink content',
  'delete any video files',
  'delete own announcement content',
  'delete own audio files',
  'delete own basic_page content',
  'delete own class content',
  'delete own class_link_group content',
  'delete own contact content',
  'delete own department content',
  'delete own document files',
  'delete own editorial_team content',
  'delete own file content',
  'delete own image files',
  'delete own info_homepage content',
  'delete own page content',
  'delete own person content',
  'delete own policy content',
  'delete own policy_area content',
  'delete own policy_implementation content',
  'delete own policy_input content',
  'delete own policy_keyfile content',
  'delete own priority content',
  'delete own publication content',
  'delete own topic content',
  'delete own toplink content',
  'delete own video files',
  'delete revisions',
  'delete terms in 2',
  'delete terms in 3',
  'delete terms in 4',
  'delete terms in 5',
  'delete terms in 6',
  'delete terms in 7',
  'display drupal links',
  'download any audio files',
  'download any document files',
  'download any image files',
  'download any video files',
  'download own audio files',
  'download own document files',
  'download own image files',
  'download own video files',
  'edit any announcement content',
  'edit any audio files',
  'edit any basic_page content',
  'edit any class content',
  'edit any class_link_group content',
  'edit any contact content',
  'edit any department content',
  'edit any document files',
  'edit any editorial_team content',
  'edit any file content',
  'edit any image files',
  'edit any info_homepage content',
  'edit any page content',
  'edit any person content',
  'edit any policy content',
  'edit any policy_area content',
  'edit any policy_implementation content',
  'edit any policy_input content',
  'edit any policy_keyfile content',
  'edit any priority content',
  'edit any publication content',
  'edit any site_menu bean',
  'edit any topic content',
  'edit any toplink content',
  'edit any video files',
  'edit bean view mode',
  'edit link settings',
  'edit meta tags',
  'edit own announcement content',
  'edit own audio files',
  'edit own basic_page content',
  'edit own class content',
  'edit own class_link_group content',
  'edit own comments',
  'edit own contact content',
  'edit own department content',
  'edit own document files',
  'edit own editorial_team content',
  'edit own file content',
  'edit own image files',
  'edit own info_homepage content',
  'edit own page content',
  'edit own person content',
  'edit own policy content',
  'edit own policy_area content',
  'edit own policy_implementation content',
  'edit own policy_input content',
  'edit own policy_keyfile content',
  'edit own priority content',
  'edit own publication content',
  'edit own topic content',
  'edit own toplink content',
  'edit own video files',
  'edit terms in 2',
  'edit terms in 3',
  'edit terms in 4',
  'edit terms in 5',
  'edit terms in 6',
  'edit terms in 7',
  'export nodes',
  'export own nodes',
  'flush caches',
  'generate features',
  'import media',
  'migration information',
  'moderate content from draft to needs_review',
  'moderate content from needs_review to draft',
  'moderate content from needs_review to published',
  'moderate content from needs_review to validated',
  'moderate content from published to archived',
  'moderate content from validated to published',
  'multisite_workbench_moderation_view_bulk_update',
  'node-specific print configuration',
  'notify of path changes',
  'opt-in or out of tracking',
  'override default scheduler time',
  'override player dimensions',
  'post comments',
  'provide translation services',
  're convert video',
  'rename features',
  'revert revisions',
  'schedule (un)publishing of nodes',
  'search content',
  'select account cancellation method',
  'send unlimited emails',
  'show format selection for comment',
  'show format selection for file',
  'show format selection for node',
  'show format selection for rules_config',
  'show format selection for taxonomy_term',
  'show format selection for user',
  'show format tips',
  'show more format tips link',
  'skip CAPTCHA',
  'skip comment approval',
  'submit translation jobs',
  'toggle field translatability',
  'translate admin strings',
  'translate any entity',
  'translate content',
  'translate interface',
  'translate node entities',
  'translate user-defined strings',
  'use advanced search',
  'use default thumb',
  'use editor',
  'use flag import',
  'use media wysiwyg',
  'use PHP for label patterns',
  'use PHP for tracking visibility',
  'use text format basic_html',
  'use text format filtered_html',
  'use text format full_html',
  'use workbench_moderation my drafts tab',
  'use workbench_moderation needs review tab',
  'view advanced help index',
  'view advanced help popup',
  'view advanced help topic',
  'view all unpublished content',
  'view any site_menu bean',
  'view bean page',
  'view bean revisions',
  'view files',
  'view moderation history',
  'view moderation messages',
  'view own files',
  'view own private files',
  'view own unpublished content',
  'view private files',
  'view rate results page',
  'view revisions',
  'view scheduled content',
  'view the administration theme',
);
