<?php
$permissions['editor'] = array(
  'access administration menu',
  'access administration pages',
  'access broken links report',
  'access content',
  'access content overview',
  'access contextual links',
  'access helper content types',
  'access own broken links report',
  'administer comments',
  'administer contexts',
  'administer files',
  'administer menu',
  'administer nodes',
  'administer taxonomy',
  'create announcement content',
  'create article content',
  'create banner_quote content',
  'create banner_video content',
  'create contact content',
  'create department content',
  'create editorial_team content',
  'create featured_item content',
  'create files',
  'create person content',
  'create policy content',
  'create policy_area content',
  'create policy_implementation content',
  'create policy_input content',
  'create policy_keyfile content',
  'create priority content',
  'create priority_policy_area content',
  'create publication content',
  'create topic content',
  'create toplink content',
  'delete any announcement content',
  'delete any article content',
  'delete any audio files',
  'delete any banner_quote content',
  'delete any banner_video content',
  'delete any contact content',
  'delete any department content',
  'delete any document files',
  'delete any editorial_team content',
  'delete any featured_item content',
  'delete any image files',
  'delete any person content',
  'delete any policy content',
  'delete any policy_area content',
  'delete any policy_implementation content',
  'delete any policy_input content',
  'delete any policy_keyfile content',
  'delete any priority content',
  'delete any priority_policy_area content',
  'delete any publication content',
  'delete any topic content',
  'delete any toplink content',
  'delete any video files',
  'delete own announcement content',
  'delete own article content',
  'delete own audio files',
  'delete own banner_quote content',
  'delete own banner_video content',
  'delete own contact content',
  'delete own department content',
  'delete own document files',
  'delete own editorial_team content',
  'delete own featured_item content',
  'delete own image files',
  'delete own person content',
  'delete own policy content',
  'delete own policy_area content',
  'delete own policy_implementation content',
  'delete own policy_input content',
  'delete own policy_keyfile content',
  'delete own priority content',
  'delete own priority_policy_area content',
  'delete own publication content',
  'delete own topic content',
  'delete own toplink content',
  'delete own video files',
  'delete revisions',
  'delete terms in 2',
  'delete terms in 3',
  'delete terms in 4',
  'delete terms in 6',
  'delete terms in 7',
  'delete terms in 8',
  'delete terms in 9',
  'download any audio files',
  'download any document files',
  'download any image files',
  'download any video files',
  'download own audio files',
  'download own document files',
  'download own image files',
  'download own video files',
  'edit any announcement content',
  'edit any article content',
  'edit any audio files',
  'edit any banner_quote content',
  'edit any banner_video content',
  'edit any contact content',
  'edit any department content',
  'edit any document files',
  'edit any editorial_team content',
  'edit any featured_item content',
  'edit any person content',
  'edit any policy content',
  'edit any policy_area content',
  'edit any policy_implementation content',
  'edit any policy_input content',
  'edit any policy_keyfile content',
  'edit any priority content',
  'edit any priority_policy_area content',
  'edit any publication content',
  'edit any topic content',
  'edit any toplink content',
  'edit any video files',
  'edit meta tags',
  'edit own announcement content',
  'edit own article content',
  'edit own audio files',
  'edit own banner_quote content',
  'edit own banner_video content',
  'edit own contact content',
  'edit own department content',
  'edit own document files',
  'edit own editorial_team content',
  'edit own featured_item content',
  'edit own image files',
  'edit own person content',
  'edit own policy content',
  'edit own policy_area content',
  'edit own policy_implementation content',
  'edit own policy_input content',
  'edit own policy_keyfile content',
  'edit own priority content',
  'edit own priority_policy_area content',
  'edit own publication content',
  'edit own topic content',
  'edit own toplink content',
  'edit own video files',
  'edit terms in 2',
  'edit terms in 3',
  'edit terms in 4',
  'edit terms in 6',
  'edit terms in 7',
  'edit terms in 8',
  'edit terms in 9',
  'export nodes',
  'flush caches',
  'moderate content from draft to needs_review',
  'moderate content from needs_review to draft',
  'moderate content from needs_review to published',
  'moderate content from needs_review to validated',
  'moderate content from published to archived',
  'moderate content from validated to published',
  'revert revisions',
  'show format selection for comment',
  'show format selection for file',
  'show format selection for node',
  'show format selection for taxonomy_term',
  'show format selection for user',
  'show format tips',
  'show more format tips link',
  'use text format basic_html',
  'use text format filtered_html',
  'use text format full_html',
  'use workbench_moderation my drafts tab',
  'use workbench_moderation needs review tab',
  'version management edits',
  'view all unpublished content',
  'view files',
  'view own files',
  'view own private files',
  'view own unpublished content',
  'view private files',
  'view revisions',
  'view the administration theme',
);
