<?php
/**
 * @file
 * Contains permissions export for role site manager.
 */

$permissions['site manager'] = array(
  'accept translation jobs',
  'access bean overview',
  'access ecas import users function',
  'access helper content types',
  'administer content translations',
  'administer permissions',
  'administer tmgmt',
  'administer translation tasks',
  'administer users',
  'bypass node access',
  'bypass workbench moderation',
  'configure helper content types',
  'create basic_page content',
  'create info_homepage content',
  'create translation jobs',
  'delete any basic_page content',
  'delete any info_homepage content',
  'delete own basic_page content',
  'delete own info_homepage content',
  'edit any basic_page content',
  'edit any info_homepage content',
  'edit any site_menu bean',
  'edit own basic_page content',
  'edit own info_homepage content',
  'provide translation services',
  'submit translation jobs',
  'translate admin strings',
  'translate any entity',
  'translate bean entities',
  'translate content',
  'translate interface',
  'translate node entities',
  'translate taxonomy_term entities',
  'translate user-defined strings',
  'view all unpublished content',
  'view any site_menu bean',
  'view bean page',
);
