<?php
$permissions['authenticated user'] = array(
  'access ckeditor link',
  'access comments',
  'access content',
  'access media browser',
  'access PDF version',
  'access print',
  'access send by email',
  'access site-wide contact form',
  'access user contact forms',
  'access user profiles',
  'access workbench',
  'post comments',
  'search content',
  'show format selection for file',
  'show format selection for node',
  'skip comment approval',
  'use advanced search',
  'use media wysiwyg',
  'use text format basic_html',
  'use text format filtered_html',
  'use text format full_html',
  'view files',
  'view moderation history',
  'view moderation messages',
  'view own unpublished content',
  'view revisions',
);
