<?php
$permissions['contributor'] = array(
  'access administration menu',
  'access administration pages',
  'access helper content types',
  'access workbench',
  'create announcement content',
  'create class content',
  'create class_link_group content',
  'create contact content',
  'create department content',
  'create editorial_team content',
  'create file content',
  'create files',
  'create page content',
  'create person content',
  'create policy content',
  'create policy_area content',
  'create policy_implementation content',
  'create policy_input content',
  'create policy_keyfile content',
  'create priority content',
  'create publication content',
  'create topic content',
  'create toplink content',
  'delete own announcement content',
  'delete own audio files',
  'delete own class content',
  'delete own class_link_group content',
  'delete own contact content',
  'delete own department content',
  'delete own document files',
  'delete own editorial_team content',
  'delete own file content',
  'delete own image files',
  'delete own page content',
  'delete own person content',
  'delete own policy content',
  'delete own policy_area content',
  'delete own policy_implementation content',
  'delete own policy_input content',
  'delete own policy_keyfile content',
  'delete own priority content',
  'delete own publication content',
  'delete own topic content',
  'delete own toplink content',
  'delete own video files',
  'download any audio files',
  'download any document files',
  'download any image files',
  'download any video files',
  'download own audio files',
  'download own document files',
  'download own image files',
  'download own video files',
  'edit any announcement content',
  'edit any audio files',
  'edit any class content',
  'edit any class_link_group content',
  'edit any contact content',
  'edit any department content',
  'edit any document files',
  'edit any editorial_team content',
  'edit any file content',
  'edit any image files',
  'edit any page content',
  'edit any person content',
  'edit any policy content',
  'edit any policy_area content',
  'edit any policy_implementation content',
  'edit any policy_input content',
  'edit any policy_keyfile content',
  'edit any priority content',
  'edit any publication content',
  'edit any topic content',
  'edit any toplink content',
  'edit any video files',
  'edit own announcement content',
  'edit own audio files',
  'edit own class content',
  'edit own class_link_group content',
  'edit own contact content',
  'edit own department content',
  'edit own document files',
  'edit own editorial_team content',
  'edit own file content',
  'edit own image files',
  'edit own page content',
  'edit own person content',
  'edit own policy content',
  'edit own policy_area content',
  'edit own policy_implementation content',
  'edit own policy_input content',
  'edit own policy_keyfile content',
  'edit own priority content',
  'edit own publication content',
  'edit own topic content',
  'edit own toplink content',
  'edit own video files',
  'moderate content from draft to needs_review',
  'moderate content from needs_review to draft',
  'revert revisions',
  'use workbench_moderation my drafts tab',
  'use workbench_moderation needs review tab',
  'view all unpublished content',
  'view any site_menu bean',
  'view moderation history',
  'view moderation messages',
  'view own files',
  'view own private files',
  'view own unpublished content',
  'view revisions',
);
