<?php
$permissions['contributor'] = array(
  'access helper content types',
  'access own broken links report',
  'access workbench',
  'create announcement content',
  'create article content',
  'create files',
  'create policy content',
  'create policy_area content',
  'create policy_implementation content',
  'create policy_input content',
  'create policy_keyfile content',
  'create priority content',
  'create priority_policy_area content',
  'delete any policy_area content',
  'delete any policy_implementation content',
  'delete any policy_keyfile content',
  'delete any priority content',
  'delete own announcement content',
  'delete own article content',
  'delete own image files',
  'delete own policy content',
  'delete own policy_area content',
  'delete own policy_implementation content',
  'delete own policy_input content',
  'delete own policy_keyfile content',
  'delete own priority content',
  'delete own priority_policy_area content',
  'edit any announcement content',
  'edit any policy content',
  'edit any policy_area content',
  'edit any policy_input content',
  'edit any policy_keyfile content',
  'edit any priority content',
  'edit any priority_policy_area content',
  'edit own announcement content',
  'edit own article content',
  'edit own image files',
  'edit own policy content',
  'edit own policy_area content',
  'edit own policy_implementation content',
  'edit own policy_input content',
  'edit own policy_keyfile content',
  'edit own priority content',
  'edit own priority_policy_area content',
  'moderate content from draft to needs_review',
  'moderate content from needs_review to draft',
  're convert video',
  'revert revisions',
  'show format selection for comment',
  'show format selection for file',
  'show format selection for node',
  'show format selection for taxonomy_term',
  'show format selection for user',
  'show format tips',
  'show more format tips link',
  'use text format basic_html',
  'use text format filtered_html',
  'use text format full_html',
  'use workbench_moderation my drafts tab',
  'use workbench_moderation needs review tab',
  'version management edits',
  'view all unpublished content',
  'view moderation history',
  'view moderation messages',
  'view own files',
  'view own private files',
  'view own unpublished content',
  'view revisions',
);
