<?php
/**
 * @file
 * dt_topic.features.inc
 */

/**
 * Implements hook_node_info().
 */
function dt_topic_node_info() {
  $items = array(
    'topic' => array(
      'name' => t('Topic'),
      'base' => 'node_content',
      'description' => t('Topic content type for dt.'),
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
  );
  drupal_alter('node_info', $items);
  return $items;
}
