<?php
/**
 * @file
 * dt_core_info.variable.inc
 */

/**
 * Implements hook_variable_realm_default_variables().
 */
function dt_core_info_variable_realm_default_variables() {
  $realm_variables = array();
  // English.
  $realm_variables['language']['en'] = array(
    'site_name' => 'European Commission Beta',
    'site_slogan' => 'Policies, information and services',
  );
  // Bulgarian.
  $realm_variables['language']['bg'] = array(
    "site_name" => "European Commission Beta",
    "site_slogan" => "Политики, информация и услуги",
  );
  // Czech.
  $realm_variables['language']['cs'] = array(
    "site_name" => "European Commission Beta",
    "site_slogan" => "Oblasti politiky, informace a služby",
  );
  // Danish.
  $realm_variables['language']['da'] = array(
    "site_name" => "European Commission Beta",
    "site_slogan" => "Politikker, oplysninger og tjenester",
  );
  // German.
  $realm_variables['language']['de'] = array(
    "site_name" => "European Commission Beta",
    "site_slogan" => "Politikfelder, Informationen und Dienste",
  );
  // Estonian.
  $realm_variables['language']['et'] = array(
    "site_name" => "European Commission Beta",
    "site_slogan" => "Poliitikavaldkonnad, teave ja teenused",
  );
  // Greek.
  $realm_variables['language']['el'] = array(
    "site_name" => "European Commission Beta",
    "site_slogan" => "Πολιτικές, πληροφορίες και υπηρεσίες",
  );
  // Spanish.
  $realm_variables['language']['es'] = array(
    "site_name" => "European Commission Beta",
    "site_slogan" => "Políticas, información y servicios",
  );
  // French.
  $realm_variables['language']['fr'] = array(
    "site_name" => "European Commission Beta",
    "site_slogan" => "Politiques, informations et services",
  );
  // Irish.
  $realm_variables['language']['ga'] = array(
    "site_name" => "European Commission Beta",
    "site_slogan" => "Beartais, eolas agus seirbhísí",
  );
  // Croatian.
  $realm_variables['language']['hr'] = array(
    "site_name" => "European Commission Beta",
    "site_slogan" => "Politike, informacije i službe",
  );
  // Italian.
  $realm_variables['language']['it'] = array(
    "site_name" => "European Commission Beta",
    "site_slogan" => "Politiche, informazioni e servizi",
  );
  // Latvian.
  $realm_variables['language']['lv'] = array(
    "site_name" => "European Commission Beta",
    "site_slogan" => "Politikas jomas, informācija un dienesti",
  );
  // Lithuanian.
  $realm_variables['language']['lt'] = array(
    "site_name" => "European Commission Beta",
    "site_slogan" => "Politika, informacija ir paslaugos",
  );
  // Hungarian.
  $realm_variables['language']['hu'] = array(
    "site_name" => "European Commission Beta",
    "site_slogan" => "Szakpolitikák, információk és szolgálatok",
  );
  // Maltese.
  $realm_variables['language']['mt'] = array(
    "site_name" => "European Commission Beta",
    "site_slogan" => "Politiki, informazzjoni u servizzi",
  );
  // Maltese.
  $realm_variables['language']['nl'] = array(
    "site_name" => "European Commission Beta",
    "site_slogan" => "Beleid, informatie en diensten",
  );
  // Polish.
  $realm_variables['language']['pl'] = array(
    "site_name" => "European Commission Beta",
    "site_slogan" => "Obszary polityki, informacje i usługi",
  );
  // Portuguese.
  $realm_variables['language']['pt-pt'] = array(
    "site_name" => "European Commission Beta",
    "site_slogan" => "Políticas, informações e serviços",
  );
  // Romanian.
  $realm_variables['language']['ro'] = array(
    "site_name" => "European Commission Beta",
    "site_slogan" => "Politici, informații și servicii",
  );
  // Slovak.
  $realm_variables['language']['sk'] = array(
    "site_name" => "European Commission Beta",
    "site_slogan" => "Politiky, informácie a služby",
  );
  // Slovenian.
  $realm_variables['language']['sl'] = array(
    "site_name" => "European Commission Beta",
    "site_slogan" => "Politike, informacije in službe",
  );
  // Finnish.
  $realm_variables['language']['fi'] = array(
    "site_name" => "European Commission Beta",
    "site_slogan" => "Politiikan alat, palvelut, tietolähteet",
  );
  // Swedish.
  $realm_variables['language']['sv'] = array(
    "site_name" => "European Commission Beta",
    "site_slogan" => "Politikområden, information och tjänster",
  );

  return $realm_variables;
}
