<?php

/**
 * @file
 * dt_social_media_sharing.module
 */

/**
 * Implements hook_preprocess_HOOK().
 *
 * This will add the required code to the header so that the webtools social
 * select is always loaded.
 */
function dt_social_media_sharing_preprocess_page(&$variables) {
  if (!path_is_admin(current_path())) {
    drupal_add_js(variable_get('dt_social_media_sharing_js_url', '//europa.eu/webtools/load.js'), 'external');
    drupal_add_html_head([
      '#tag' => 'script',
      '#value' => '{
        "service" : "sbkm",
        "popup" : false,
        "selection": true
      }',
      '#attributes' => [
        'type' => 'application/json',
      ],
    ], 'social_media_select');
  }
}

/**
 * Implements hook_block_info().
 */
function dt_social_media_sharing_block_info() {
  $blocks = [];
  $blocks['social_media_sharing']['info'] = t('Social Media Sharing (horizontal)');
  $blocks['social_media_sharing_vertical']['info'] = t('Social Media Sharing (vertical)');
  return $blocks;
}

/**
 * Implements hook_block_configure().
 */
function dt_social_media_sharing_block_configure($delta = '') {
  $form = [];
  switch ($delta) {
    case 'social_media_sharing':
      // Text field form element.
      $form['dt_social_media_sharing_json_code'] = [
        '#type' => 'textarea',
        '#title' => t('Insert webtools object'),
        '#description' => t('Copy paste Webtools - Social Bookmark code'),
        '#default_value' => variable_get('dt_social_media_sharing_json_code', _dt_social_media_sharing_default_json()),
        '#wysiwyg' => FALSE,
        '#weight' => 0,
      ];

      $form['dt_social_media_sharing_js_url'] = [
        '#type' => 'textfield',
        '#title' => t('External Web Tools Url'),
        '#default_value' => variable_get('dt_social_media_sharing_js_url', '//europa.eu/webtools/load.js'),
        '#description' => t('This is required in order for it to work.'),
        '#required' => TRUE,
        '#weight' => 1,
      ];
      break;
  }

  return $form;
}

/**
 * Implements hook_block_save().
 */
function dt_social_media_sharing_block_save($delta = '', $edit = []) {
  switch ($delta) {
    case 'social_media_sharing':
      if ($edit['dt_social_media_sharing_json_code'] && (!empty($edit['dt_social_media_sharing_json_code']))) {
        variable_set('dt_social_media_sharing_json_code', $edit['dt_social_media_sharing_json_code']);
      }
      variable_set('dt_social_media_sharing_js_url', $edit['dt_social_media_sharing_js_url']);
      break;
  }
}

/**
 * Implements hook_block_view().
 */
function dt_social_media_sharing_block_view($delta = '') {
  $block = [];

  if (in_array($delta, ['social_media_sharing', 'social_media_sharing_vertical'])) {
    drupal_add_js(variable_get('dt_social_media_sharing_js_url', '//europa.eu/webtools/load.js'), 'external');
    $class = ($delta == 'social_media_sharing') ? 'horizontal' : 'vertical';
    $block['content'] = '<div class="social-media-links--webtool-' . $class . '">' . _dt_social_media_sharing_view_helper() . '</div>';
  }

  return $block;
}

/**
 * Generate the content of the social media sharing block.
 */
function _dt_social_media_sharing_view_helper() {
  $text = '<span class="social-media-links__label">' . t('Share this page') . ':</span>';
  $text .= variable_get('dt_social_media_sharing_json_code', _dt_social_media_sharing_default_json());

  return $text;
}

/**
 * Helper function that holds default web tools SocialBookmarks JSON.
 *
 * @return string
 *   Creates and returns default json object.
 */
function _dt_social_media_sharing_default_json() {
  return '<script type="application/json">
  {
    "service": "sbkm",
    "popup": false,
    "sharing": true,
    "selection": true,
    "to": [
      "more",
      "twitter",
      "facebook",
      "googleplus",
      "linkedin",
      "e-mail"
    ],
    "stats": true,
    "css": {
      "list": "wtShareList"
    }
  }
</script>';
}

/**
 * Implements hook_ds_fields_info().
 *
 * SocialMedia Bookmark field from Web tools,
 * this field will be used by several content types
 * and possible in both Info + Pol websites.
 */
function dt_social_media_sharing_ds_fields_info($entity_type) {
  $ds_fields = [];

  $ds_fields['social_bookmark_webtools'] = [
    'title' => t('Social Bookmark Webtools (horizontal)'),
    'field_type' => DS_FIELD_TYPE_BLOCK,
    'properties' => [
      'block' => 'dt_social_media_sharing|social_media_sharing',
      'block_render' => '1',
    ],
    'ui_limit' => '',
    'entities' => [
      'node' => 'node',
    ],
  ];

  $ds_fields['social_bookmark_webtools_vertical'] = [
    'title' => t('Social Bookmark Webtools (vertical)'),
    'field_type' => DS_FIELD_TYPE_BLOCK,
    'properties' => [
      'block' => 'dt_social_media_sharing_vertical|social_media_sharing_vertical',
      'block_render' => '1',
    ],
    'ui_limit' => '',
    'entities' => [
      'node' => 'node',
    ],
  ];

  return ['node' => $ds_fields];
}
