<?php

/**
 * Implements hook_permission().
 */
function dt_node_settings_permission() {
  return array(
    'configure helper content types' => array(
      'title' => t('Configure helper content types'),
      'description' => t('Allow configurations of helper content types'),
    ),
    'access helper content types' => array(
      'title' => t('Access helper content types'),
      'description' => t('Allow access to full view of helper content types'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function dt_node_settings_menu() {
  $items = array();
  $items['admin/config/content/helper_node_types/settings'] = array(
    'title' => t('Helper content types settings'),
    'description' => t('Indicate helper content types for the system.'),
    'page callback' => 'drupal_get_form',
    'access arguments' => array('configure helper content types'),
    'page arguments' => array('dt_node_settings_helpers_overall'),
    'file' => 'dt_node_settings.admin.inc',
    'file path' => drupal_get_path('module', 'dt_node_settings'),
  );
  return $items;
}

/**
 * Implements hook_form_alter().
 */
function dt_node_settings_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'node_type_form' && user_access('access helper content types')) {
    $form['dt_node_settings'] = array(
      '#type' => 'fieldset',
      '#title' => t('DT specific node settings'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
      '#group' => 'additional_settings',
    );

    $form['dt_node_settings']['helper_content_type'] = array(
      '#type' => 'checkbox',
      '#title' => t('Helper content type'),
      '#default_value' => variable_get('helper_node_type_' . $form['#node_type']->type, 0),
      '#options' => array(
        0 => t('Disabled'),
        1 => t('Enabled'),
      ),
      '#description' => t('Require special permissions to access to full view of pages of this type.'),
    );

    $form['#submit'][] = 'dt_node_settings_helpers_single_submit';
  }
}

/**
 * Helper saving 'helper' state per content type.
 */
function dt_node_settings_helpers_single_submit($form, &$form_state) {
  variable_set('helper_node_type_' . $form['#node_type']->type, $form_state['values']['helper_content_type']);
}

/**
 * Implements hook_menu_alter().
 */
function dt_node_settings_menu_alter(&$items) {
  // Disable the '/node' page.
  $items['node']['access callback'] = FALSE;

  // Use our own access callback for the 'node/%node' page.
  $items['node/%node']['access callback'] = 'dt_node_settings_node_access_callback';
}

/**
 * Access callback for the node detail page.
 */
function dt_node_settings_node_access_callback($op, $node) {
  // Deny access to the full view mode on helper content type nodes.

  if ($op == 'view' && _content_type_is_helper($node->type) && !user_access('access helper content types')) {
    return FALSE;
  }

  // Default to the regular node access callback.
  return node_access($op, $node);
}

/**
 * Returns TRUE if $node_type is a helper.
 * @param $node_type
 * @return bool
 */
function _content_type_is_helper($node_type) {
  return variable_get('helper_node_type_' . $node_type, FALSE);
}
