<?php

/**
 * Implements hook_permission().
 */
function nexteuropa_entities_permission() {
  return array(
    'configure helper content types' => array(
      'title' => t('Configure helper content types'),
      'description' => t('Allow configurations of helper content types'),
    ),
    'access helper content types' => array(
      'title' => t('Access helper content types'),
      'description' => t('Allow access to full view of helper content types'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function nexteuropa_entities_menu() {
  $items = array();
  $items['admin/config/content/nexteuropa_entities/settings'] = array(
    'title' => t('Helper content types settings'),
    'description' => t('Indicate helper content types for the system.'),
    'page callback' => 'drupal_get_form',
    'access arguments' => array('administer site configuration'),
    'page arguments' => array('helper_content_types_settings'),
    'file' => 'nexteuropa_entities.admin.inc',
    'file path' => drupal_get_path('module', 'nexteuropa_entities'),
  );
  return $items;
}

/**
 * Implements hook_form_alter().
 */
function nexteuropa_entities_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'node_type_form') {
    $form['nexteuropa_settings'] = array(
      '#type' => 'fieldset',
      '#title' => t('NextEuropa settings'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
      '#group' => 'additional_settings',
    );

    $form['nexteuropa_settings']['helper_content_type'] = array(
      '#type' => 'checkbox',
      '#title' => t('Helper content type'),
      '#default_value' => variable_get('helper_node_type_' . $form['#node_type']->type, 0),
      '#options' => array(
        0 => t('Disabled'),
        1 => t('Enabled'),
      ),
      '#description' => t('Disallow access to full view of pages of this type.'),
    );

    $form['#submit'][] = '_helper_content_types_single_submit';
  }
}

/**
 * Helper saving 'helper' state per content type.
 */
function _helper_content_types_single_submit($form, &$form_state) {
  variable_set('helper_node_type_' . $form['#node_type']->type, $form_state['values']['helper_content_type']);
}

/**
 * Implements hook_page_alter().
 *
 * We use this because it is only called once per request.
 */
function nexteuropa_entities_page_alter(&$page) {
  // Get the node we are about to display.
  if ($node = menu_get_object('node')) {
    if (!user_access('access helper content types') && _content_type_is_helper($node->type)) {
      drupal_goto(MENU_NOT_FOUND);
    }
  }
}

/**
 * Returns TRUE if $node_type is a helper.
 * @param $node_type
 * @return bool
 */
function _content_type_is_helper($node_type) {
  $node_types = node_type_get_names();
  foreach($node_types as $type => $label) {
    if ($type == $node_type) {
      return variable_get('helper_node_type_' . $type, 0) ? TRUE : FALSE;
    }
  }
  return FALSE;
}