<?php

/**
 * Implements hook_permission().
 */
function nexteuropa_entities_permission() {
  return array(
    'indicate helper content types' => array(
      'title' => t('Helper content types'),
      'description' => t('Allow admin users to indicate helper content types'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function nexteuropa_entities_menu() {
  $items = array();
  $items['admin/config/content/nexteuropa_entities/settings'] = array(
    'title' => t('Helper content types'),
    'description' => t('Indicate helper content types for the system.'),
    'page callback' => 'drupal_get_form',
    'access arguments' => array('administer site configuration'),
    'page arguments' => array('nexteuropa_entities_settings'),
    'file' => 'nexteuropa_entities.admin.inc',
    'file path' => drupal_get_path('module', 'nexteuropa_entities'),
  );
  return $items;
}


/**
 * Implements hook_form_alter().
 */
function nexteuropa_entities_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'node_type_form') {
    $form['nexteuropa_settings'] = array(
      '#type' => 'fieldset',
      '#title' => t('NextEuropa settings'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
      '#group' => 'additional_settings',
    );

    $form['nexteuropa_settings']['helper_content_type'] = array(
      '#type' => 'checkbox',
      '#title' => t('Helper content type'),
      '#default_value' => variable_get('nexteuropa_entities_helper_node_type_' . $form['#node_type']->type, FALSE),
      '#options' => array(
        0 => t('Disabled'),
        1 => t('Enabled'),
      ),
      '#description' => t('Disallow anonymous users from viewing the full page of this content.'),
    );
    // Add a submit handler function.
    $form['#submit'][] = '_content_type_helper_set';
  }
}

/**
 * Helper saving 'helper' state per content type.
 */
function _content_type_helper_set($form, &$form_state) {
  variable_set('nexteuropa_entities_helper_node_type_' . $form['#node_type']->type, $form_state['values']['helper_content_type']);
}

/**
 * Implements hook_page_alter().
 *
 * We use this because it is only called once per request.
 */
function nexteuropa_entities_page_alter(&$page) {
  // Get the node we are about to display.
  if ($node = menu_get_object('node')) {
    // Check if it is in the helper list.
    if (_content_type_is_helper($node->type) && !user_is_logged_in()) {
      // Redirect to the 404 page.
      drupal_goto(MENU_NOT_FOUND);
    }
  }
}

/**
 * Helper returning TRUE if a node type is a helper.
 * @param $node_type
 * @return bool
 */
function _content_type_is_helper($node_type) {
  $node_types = node_type_get_names();
  foreach($node_types as $type => $label) {
    if ($type == $node_type) {
      return variable_get('nexteuropa_entities_helper_node_type_' . $type, 0) ? TRUE : FALSE;
    }
  }
  return FALSE;
}