<?php
/**
 * @file
 * Code for the dt Publication feature.
 */

include_once 'dt_publication.features.inc';

/**
 * Implements hook_migrate_api().
 */
function dt_publication_migrate_api() {
  return array(
    'api' => 2,
    'groups' => array(
      'NextEuropa' => array(
        'title' => t('Stage initial content, publication types.'),
      ),
    ),
    'migrations' => array(
      'DTPublicationPublicationTypes' => array(
        'class_name' => 'DTPublicationPublicationTypesMigration',
        'group_name' => 'NextEuropa Digital Transformation',
      ),
    ),
  );
}

/**
 * Implements hook_form_alter().
 */
function dt_publication_form_alter(&$form, &$form_state, $form_id) {
  if($form_id === 'publication_node_form') {
    kpr($form);
    $form['field_core_publications']['#states'] = array(
      'visible' => array(
        ':input[name="field_publication_collection[und]"]' => array('value' => '1'),
      ),
    );
    $form['field_core_files']['#states'] = array(
      'visible' => array(
        ':input[name="field_publication_collection[und]"]' => array('value' => '0'),
      ),
    );
  }
}
