<?php
/**
 * @file
 * Views news carousel.
 */

/**
 * Implements hook_views_api().
 */
function nexteuropa_views_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * Implements hook_views_plugins().
 */
function nexteuropa_views_views_plugins() {
  $path = drupal_get_path('module', 'nexteuropa_views');

  $plugins = array(
    'style' => array(
      'nexteuropa_bem_listing' => array(
        'title' => t('Nexteuropa BEM listing'),
        'help' => t('Display items using BEM Listing component.'),
        'path' => $path,
        'handler' => 'views_plugin_style_nexteuropa_listing',
        'uses row plugin' => TRUE,
        'uses options' => TRUE,
        'uses grouping' => TRUE,
        'type' => 'normal',
      ),
    ),
  );

  return $plugins;
}

/**
 * Implements template_preprocess_HOOK().
 */
// function template_preprocess_views_view_news_carousel(&$vars) {
//   $vars['titles'] = array();
//   $path = drupal_get_path('module', 'waat_news_carousel');
//   drupal_add_js($path . '/js/news-carousel.js', array('type' => 'file', 'scope' => 'footer'));
//
//   // Render more button inside the template.
//   $vars['more'] = $_SESSION['waat_news_carousel_more'];
//   unset($_SESSION['waat_news_carousel_more']);
//
//   // Create array of titles
//   foreach ($vars['view']->result as $count => $item) {
//     $node = node_load($item->nid);
//     $vars['titles'][$count] = $node->title;
//   }
// }

/**
 * Implements template_preprocess_HOOK().
 */
// function waat_news_carousel_process_views_view(&$vars) {
//   if ($vars['view']->style_plugin->plugin_name == 'waat_news_carousel') {
//     $_SESSION['waat_news_carousel_more'] = $vars['more'];
//     $vars['more'] = NULL;
//   }
// }
