<?php

/**
 * @file
 * DT Policy input install file.
 */

/**
 * Implements hook_install().
 */
function dt_tender_default_install() {
  $t = get_t();
  drupal_set_message($t('NextEuropa tender feature is installed on your site.'));
}

/**
 * Implements hook_uninstall().
 */
function dt_tender_default_uninstall() {
  drupal_set_message(t('NextEuropa tender feature is uninstalled on your site.'));
}
