<?php
/**
 * @file
 * Code for the DT Policy input feature.
 */

include_once 'dt_law.features.inc';

/**
 * Helper function for DT Law convert.
 */
function dt_law_inabc() {
  $query = new EntityFieldQuery();

  $result = $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'policy_implementation')
    ->fieldCondition('field_policy_imp_type', 'value', 'law', '=')
    ->execute();

  if (isset($result['node'])) {
    $nids = array_keys($result['node']);
    foreach ($nids as $nid) {
      $old_node = node_load($nid);
      if ($old_node->type == 'law') {
        continue;
      }
      kpr($old_node);
      $new_nid = node_convert_node_convert($nid, 'law',
        array(
          'field_policy_imp_introduction',
          'field_policy_imp_status',
        ),
        array(
          'field_core_description',
          'field_law_status',
        ),
          FALSE
      );
      if ($new_nid) {
        $node = node_load($new_nid);
        kpr($node);
        // Status converter.
        $node->field_law_status = $old_node->field_policy_imp_status;
        foreach ($old_node->field_policy_imp_status as $lang => $item) {
          switch ($item[0]['value']) {
            case 'adopted':
              $node->field_law_status[$lang][0]['value'] = 'in_force';
              break;

            case 'proposed':
            default:
              $node->field_law_status[$lang][0]['value'] = 'proposed';
              break;

          }
        }
        // Description converter.
        foreach ($old_node->field_policy_imp_introduction as $lang => $item) {
          $node->field_core_description[$lang][0]['value'] = strip_tags($item[0]['value']);
        }
        node_save($node);
        kpr($node);
      }
      break;

    }
  }
}