<?php
/**
 * @file
 * DT Policy input install file.
 */

/**
 * Implements hook_install().
 */
function dt_impact_assessment_default_install() {
  $t = get_t();
  drupal_set_message($t('NextEuropa impact_assessment feature is installed on your site.'));
}

/**
 * Implements hook_uninstall().
 */
function dt_impact_assessment_default_uninstall() {
  drupal_set_message(t('NextEuropa impact_assessment feature is uninstalled on your site.'));
}
