<?php

/**
 * @file
 * NextEuropa EuroVoc install file.
 */

/**
 * Implements hook_install().
 */
function nexteuropa_eurovoc_install() {
  $t = get_t();
  drupal_set_message($t('NextEuropa EuroVoc feature is installed on your site.'));
}

/**
 * Implements hook_uninstall().
 */
function nexteuropa_eurovoc_uninstall() {
  drupal_set_message(t('NextEuropa EuroVoc feature has been uninstalled from your site.'));
}
