<?php
/**
 * @file
 * Code for the dt_page feature.
 */

include_once 'dt_page.features.inc';

/**
 * Implements hook_ds_pre_render_alter().
 *
 * Before we render the page, we check if we should even display the in page
 * navigation.
 */
function dt_page_ds_pre_render_alter(&$layout_render_array, $context) {
  // If the other conditions meet.
  if ($context['entity']->type == 'basic_page' && $context['view_mode'] == 'full') {
    $in_page = $context['entity']->field_core_in_page_navigation[LANGUAGE_NONE][0]['value'];
    $latest = $context['entity']->field_core_latest_visibility[LANGUAGE_NONE][0]['value'];

    if ($in_page == '0') {
      // We remove the sidebar.
      unset($layout_render_array['left']);
    }
    if ($latest == 0) {
      foreach ($layout_render_array['central'] as  $key => $blocks) {
        if (isset($blocks['group_page_latest'])) {
          unset($layout_render_array['central'][$key]);
        }
      }
    }
  }
}
