<?php
/**
 * @file
 * dt_subject.features.inc
 */

/**
 * Implements hook_node_info().
 */
function dt_subject_node_info() {
  $items = array(
    'subject' => array(
      'name' => t('Subject'),
      'base' => 'node_content',
      'description' => t('Subject content type for dt.'),
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
  );
  drupal_alter('node_info', $items);
  return $items;
}
