<?php
/**
 * @file
 * DT Policy input install file.
 */

/**
 * Implements hook_install().
 */
function dt_law_default_install() {
  drupal_set_message(t('NextEuropa law feature is installed on your site.'));
}

/**
 * Implements hook_uninstall().
 */
function dt_law_default_uninstall() {
  drupal_set_message(t('NextEuropa law feature is uninstalled on your site.'));
}

/**
 * First hook_update for example.
 */
/*
function dt_law_default_update_7101() {

}
 */
