<?php
/**
 * @file
 * Contains permissions export for role site manager.
 */

$permissions['site manager'] = array(
  'accept translation jobs',
  'access bean overview',
  'access ecas import users function',
  'access helper content types',
  'administer content translations',
  'administer permissions',
  'administer themes',
  'administer tmgmt',
  'administer translation tasks',
  'administer users',
  'assign node weight',
  'bypass node access',
  'bypass workbench moderation',
  'configure helper content types',
  'configure priorities listing page',
  'create basic_page content',
  'create info_homepage content',
  'create coordination content',
  'create consultation content',
  'create funding content',
  'create guidance content',
  'create impact content',
  'create law content',
  'create tender content',
  'create translation jobs',
  'create url aliases',
  'delete any basic_page content',
  'delete any info_homepage content',
  'delete any coordination content',
  'delete any consultation content',
  'delete any funding content',
  'delete any guidance content',
  'delete any impact content',
  'delete any law content',
  'delete any tender content',
  'delete own basic_page content',
  'delete own info_homepage content',
  'delete own coordination content',
  'delete own consultation content',
  'delete own funding content',
  'delete own guidance content',
  'delete own impact content',
  'delete own law content',
  'delete own tender content',
  'edit any basic_page content',
  'edit any info_homepage content',
  'edit any site_menu bean',
  'edit own basic_page content',
  'edit own info_homepage content',
  'edit own coordination content',
  'edit own consultation content',
  'edit own funding content',
  'edit own guidance content',
  'edit own impact content',
  'edit own law content',
  'edit own tender content',
  'edit any coordination content',
  'edit any consultation content',
  'edit any funding content',
  'edit any guidance content',
  'edit any impact content',
  'edit any law content',
  'edit any tender content',
  'flush caches',
  'provide translation services',
  'submit translation jobs',
  'translate admin strings',
  'translate any entity',
  'translate bean entities',
  'translate content',
  'translate interface',
  'translate node entities',
  'translate taxonomy_term entities',
  'translate user-defined strings',
  'view all unpublished content',
  'view any site_menu bean',
  'view bean page',
  'masquerade as user',
  'masquerade as any user',
);
