<?php
/**
 * @file
 * DT wysiwyg overrides ckeditor buttons.
 */

/**
 * Implements hook_wysiwyg_editor_settings_alter().
 */
function dt_wysiwyg_wysiwyg_editor_settings_alter(&$settings, $context) {
  if ($context['profile']->editor == 'ckeditor') {
    global $base_url;
    /
    $default_buttons = $settings['toolbar'][0];

    // Remove buttons described on the ticket NEXTEUROPA-7770.
    $buttons_remove = array(
      'ShowBlocks',
      'HorizontalRule',
      'FontSize',
      'Font',
      'Smiley',
      'break',
    );
    // Loops and remove.
    foreach ($default_buttons as $button_index => $button) {
      foreach ($buttons_remove as $button_remove) {
        if ($button == $button_remove) {
          unset($default_buttons[$button_index]);
        }
      }
    }

    // Re-arrange default buttons and assign.
    $settings['toolbar'][0] = array_values($default_buttons);
    // Apply source formating when viewing html source.
    $settings['apply_source_formatting'] = 1;
    // Available default values: "p;address;pre;h2;h3;h4;h5;h6;div".
    $settings['format_tags'] = "address;h2;h3;h4;h5;h6;div";
    // Settings ckeditor to use theme css.
    $settings['contentsCss'] = array(
      '0' => $base_url . '/' . drupal_get_path('theme', 'europa') . '/css/style-sass.css',
    );
  }
}
