<?php

/**
 * @file
 * DT wysiwyg overrides ckeditor buttons.
 */

/**
 * Implements hook_ckeditor_plugin().
 */
function dt_wysiwyg_ckeditor_plugin() {
  return [
    'dt_headings' => [
      'name' => 'dt_headings',
      'desc' => t('Headings, detailed'),
      'path' => drupal_get_path('module', 'dt_wysiwyg') . '/plugins/dt_headings',
    ],
  ];
}

/**
 * Implements hook_wysiwyg_plugin().
 */
function dt_wysiwyg_wysiwyg_plugin($editor, $version) {
  if ($editor == 'ckeditor') {
    return [
      'dt_headings' => [
        'path' => drupal_get_path('module', 'dt_wysiwyg') . '/plugins/dt_headings',
        'load' => TRUE,
        'buttons' => ['dt_headings' => t('Headings, detailed')],
      ],
    ];
  }
}

/**
 * Implements hook_wysiwyg_include_directory().
 */
function dt_wysiwyg_wysiwyg_include_directory($type) {
  switch ($type) {
    case 'plugins':
      return $type;
  }
}

/**
 * Implements hook_INCLUDE_plugin().
 */
function dt_wysiwyg_dt_headings_plugin() {
  $plugins['dt_headings'] = [
    'title' => t('Headings, detailed'),
    'vendor url' => 'http://drupal.org/project/wysiwyg',
    'icon file' => 'dt_headings.png',
    'icon title' => t('Headings, detailed'),
    'settings' => [],
  ];

  return $plugins;
}

/**
 * Implements hook_wysiwyg_editor_settings_alter().
 */
function dt_wysiwyg_wysiwyg_editor_settings_alter(&$settings, $context) {

  global $base_url;

  if ($context['profile']->editor == 'ckeditor') {
    // Apply source formating when viewing html source.
    $settings['apply_source_formatting'] = 1;
    $settings['cleanup_on_startup'] = TRUE;

    // Remove formats on paste.
    $settings['forcePasteAsPlainText'] = TRUE;

    // Available default values: "p;h2;h3;h4;h5;h6".
    $settings['format_tags'] = "Paragraph;h2;h3;h4;h5;h6";

    // Change the default format p.
    $settings['format_Paragraph']['name'] = 'Paragraph';
    $settings['format_Paragraph']['element'] = 'p';

    // Settings ckeditor to use theme css.
    $settings['contentsCss'] = [
      '0' => $base_url . '/' . drupal_get_path('theme', 'europa') . '/css/style-sass-base.css',
      '1' => $base_url . '/' . drupal_get_path('theme', 'europa') . '/css/style-sass-components.css',
    ];

    $settings['bodyClass'] = 'padding-wysiwyg-body';

    // Make sure the toolbar is there.
    if (!empty($settings['toolbar'])) {
      $new_toolbar = [];
      // These are our desired groupings.
      $new_toolbar[] = ['Format', 'dt_headings'];
      $new_toolbar[] = ['Bold'];
      $new_toolbar[] = ['Link', 'NextEuropaToken', 'Unlink', 'Anchor'];
      $new_toolbar[] = ['BulletedList', 'NumberedList', 'Outdent', 'Indent'];
      $new_toolbar[] = ['media', 'Blockquote', 'Abbr', 'Table'];
      $new_toolbar[] = ['RemoveFormat'];
      $new_toolbar[] = ['Undo', 'Maximize'];
      $new_toolbar[] = [
        'lite_AcceptAll',
        'lite_RejectAll',
        'lite_AcceptOne',
        'lite_RejectOne',
        'lite_ToggleShow',
        'lite_ToggleTracking',
      ];
      $new_toolbar[] = ['Source'];

      // Replace the toolbar with our new, grouped toolbar.
      $settings['toolbar'] = $new_toolbar;
    }

    drupal_add_js($base_url . '/' . drupal_get_path('module', 'dt_wysiwyg') . '/dt_wyswyg_ckeditor_config.js');
  }
}
