<?php
/**
 * @file
 * Dt_Banner install file.
 */

/**
 * Implements hook_install().
 */
function dt_banner_install() {
  $banner_types = array(
    'dt_banner_video',
    'dt_banner_quote',
  );
  module_enable($banner_types);
}

/**
 * Update hook to revert the banners.
 */
function dt_banner_update_7101() {
  features_revert_module('dt_banner_quote');
  features_revert_module('dt_banner_video');
}
