<?php
/**
 * @file
 * dt_devtools.module
 */

/**
 * Implements hook_menu().
 */
function dt_devtools_menu() {

  $items = array();
  $items['admin/config/development/dt_devtools'] = array(
    'title' => 'Dt development toolkit',
    'description' => 'Used for testing and development.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dt_devtools_admin'),
    'access arguments' => array('administer site configuration'),
    'file' => 'inc/dt_devtools.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_page_alter().
 *
 * It will insert any js code needed for development.
 */
function dt_devtools_page_alter(&$page) {
  foreach (_dt_devtools_libs() as $lib) {
    if (variable_get('dt_devtools_webtools_' . $lib['lib_name'], FALSE)) {
      $file = drupal_get_path('module', $lib['module_name']) . $lib['file_path'];
      if (file_exists($file)) {
        drupal_add_js($file);
        drupal_set_message('dt_devtools: scope(' . $lib['scope'] . '), file
      is being loaded locally: ' . $lib['file_name'], 'warning');
      }
    }
  }
}

/**
 * Helper function to add js files.
 * @return array
 */
function _dt_devtools_libs() {
  return array(
    'load' => array(
      'module_name' => 'dt_devtools',
      'lib_name' => 'load',
      'file_name' => 'load.js',
      'file_path' => '/js/load.js',
      'scope' => 'webtools',
      'description' => t('There could be some restrictions when loading this js file.
    Select if you want to use the local version.'),
      'title' => 'Web tools (load.js)',
    ),
  );
}
