<?php
/**
 * @file
 * Code for the DT Policy input feature.
 */

include_once 'dt_guidance.features.inc';

/**
 * Helper function for DT Guidance convert.
 */
function _dt_guidance_node_convert() {
  $query = new EntityFieldQuery();

  $result = $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'policy_implementation')
    ->fieldCondition('field_policy_imp_type', 'value', 'guidance', '=')
    ->execute();

  if (isset($result['node'])) {
    $nids = array_keys($result['node']);
    foreach ($nids as $nid) {
      $old_node = node_load($nid);
      if ($old_node->type == 'guidance') {
        continue;
      }
      $new_nid = node_convert_node_convert($nid, 'guidance',
        array(
          'field_policy_imp_introduction',
        ),
        array(
          'field_core_description',
        ),
        FALSE
      );
      if ($new_nid) {
        $node = node_load($new_nid);
        // Description converter.
        foreach ($old_node->field_policy_imp_introduction as $lang => $item) {
          $node->field_core_description[$lang][0]['value'] = strip_tags($item[0]['value']);
        }
        node_save($node);
      }
    }
  }
}
