<?php
/**
 * @file
 * Code for the CWT News feature.
 */

include_once 'cwt_news.features.inc';

/**
 * Implements hook_permission().
 */
function cwt_news_permission() {
  return array(
    'edit links on aggregated news items' => array(
      'title' => t('Edit links on aggregated news items'),
      'description' => t('Allow user to edit links field on aggregated_news content type'),
    ),
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function cwt_news_form_aggregated_news_node_form_alter(&$form, &$form_state, $form_id) {
  // Disabling field_aggregated_news_link for all roles beside administrator
  // The field is only used with feeds, so noone should be able to access it.
  if (!(user_access('edit links on aggregated news items'))) {
    $form['field_aggregated_news_link']['#access'] = FALSE;
  }
}
