<?php
/**
 * @file
 * Digital Transformation Core install file.
 */

/**
 * Implements hook_install().
 */
function dt_core_install() {
}

/**
 * Implements hook_uninstall().
 */
function dt_core_uninstall() {
  $path = drupal_get_path('module', 'dt_core') . '/dt_core.info';
  $info = drupal_parse_info_file($path);
  drupal_set_message(t('NextEuropa Subject %v feature is uninstalled on your site.', array('%v' => $info['version'])));
}
